#!/usr/bin/perl

$count=0;
$last=0;

open(IMMORT,"sort -k 3 < IMMORTALS |") || die("Can't open IMMORTALS");
while (<IMMORT>) {
  if (/(\w+)\s+\d+\s+(\w+)/) {
    if ($2!=$last) {
	printf "#define %-20s %6d\n",$1,$2;
	$last=$2;
    }
  }
}
close(IMMORT);
