"""Readers for the binary player (``stash/<a-z>/<name>``) and account
(``account/<a-z>/<name>``) save files.

These are the hand-coded tagged-record formats written by ``src/player.save.c``
(``load_char_with_path``), ``src/account.c`` (``load_acct``) and
``src/objdb.c`` (``ReadObject`` / ``ReadObjList`` for carried items). Each
record is a stream of ``u16 id`` followed by a payload whose size is the C
field's size; ``player_layout.json`` (generated by ``tools/layout.c`` against
the server headers) supplies those sizes and signedness so the Python reader
matches the compiled server exactly.

Files can be read straight out of a ``.tar`` backup or from an extracted
directory tree.
"""

from __future__ import annotations

import json
import struct
import sys
import tarfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterator

from .attack import attack_name, attack_type
from .schemas import TABLES

LAYOUT: dict[str, dict[str, Any]] = json.loads(
    Path(__file__).with_name("player_layout.json").read_text(encoding="utf-8"))

# record / sub-record markers (player.save.c)
EOF_MARK, SUB_OBJECT, OBJECT, END_OF_OBJECT, END_OF_LIST, WEAR = 255, 254, 253, 252, 251, 250
AFFECT, AFFECT_END, ERROR, MAIL, VERSION_MARKER = 249, 248, 247, 246, 245
PULSE_AFFECT, PULSE_AFFECT_END = 244, 243
PULSE_COOLDOWN, PULSE_COOLDOWN_END = 242, 241
ITEM_SET_ABILITY, ITEM_SET_ABILITY_END = 240, 239
CURRENT_PLAYER_FILE_VERSION = 6

FMT = {"u8": "<B", "s8": "<b", "u16": "<H", "s16": "<h", "u32": "<I", "s32": "<i",
       "u64": "<Q", "s64": "<q", "f64": "<d", "f32": "<f"}


class FormatError(Exception):
    pass


def _bit_name(table: list[str], n: int) -> str:
    return table[n] if n < len(table) and table[n] else f"bit{n}"


def bits(value: int, table: list[str]) -> list[str]:
    """Names of the set bits in a 32-bit flag word."""
    return [_bit_name(table, i) for i in range(32) if value & (1 << i)]


def ext_bits(words: list[int], table: list[str]) -> list[str]:
    """Names of the set bits in a u32[8] extended bitvector."""
    return [_bit_name(table, w * 32 + i) for w, word in enumerate(words) for i in range(32) if word & (1 << i)]


def name_at(table: list[str], idx: int | None) -> str | None:
    """Table entry for ``idx``; ``"#<idx>"`` when out of range so the field is
    always a string."""
    if idx is None:
        return None
    return table[idx] if 0 <= idx < len(table) and table[idx] else f"#{idx}"


PROF_BASE, SKILL_BASE = 5000, 10000


def skill_entry(num: int, learned: int, table: list[str]) -> dict[str, Any]:
    """Skill numbers: <5000 skills, 5000+ weapon proficiencies (PROF_BASE),
    10000+ skills again (SKILL_BASE); see skills.c boot_class / find_skill_entry."""
    if num >= SKILL_BASE:
        return {"number": num, "kind": "skill", "name": name_at(TABLES["skills"], num - SKILL_BASE), "learned": learned}
    if num >= PROF_BASE:
        return {"number": num, "kind": "proficiency", "name": name_at(TABLES["weapon_types"], num - PROF_BASE), "learned": learned}
    kind = "spell" if table is TABLES["spells"] else "skill"
    return {"number": num, "kind": kind, "name": name_at(table, num), "learned": learned}


class Reader:
    def __init__(self, data: bytes, where: str):
        self.d = data
        self.pos = 0
        self.where = where

    def eof(self) -> bool:
        return self.pos >= len(self.d)

    def raw(self, n: int) -> bytes:
        if self.pos + n > len(self.d):
            raise FormatError(f"{self.where}: truncated at offset {self.pos} (wanted {n} bytes)")
        b = self.d[self.pos:self.pos + n]
        self.pos += n
        return b

    def num(self, kind: str) -> int | float:
        fmt = FMT[kind]
        return struct.unpack(fmt, self.raw(struct.calcsize(fmt)))[0]

    def u8(self) -> int: return self.num("u8")
    def u16(self) -> int: return self.num("u16")
    def s32(self) -> int: return self.num("s32")
    def u32(self) -> int: return self.num("u32")

    def field(self, key: str) -> Any:
        """A value whose size and signedness come from the C struct field ``key``."""
        lay = LAYOUT[key]
        if lay["kind"] == "other":
            if lay["size"] == 32:   # u32[8] extended bitvector
                return list(struct.unpack("<8I", self.raw(32)))
            raise FormatError(f"{self.where}: no decoder for {key}")
        return self.num(lay["kind"])

    def sd(self) -> str:
        """ReadSD / _ReadSS: u16 length (including NUL) then bytes."""
        n = self.u16()
        b = self.raw(n)
        b = b.split(b"\0", 1)[0]
        try:
            return b.decode("utf-8")
        except UnicodeDecodeError:
            return b.decode("latin-1")

    def time32(self) -> int:
        return self.u32()

    def counted(self, elem_size: int) -> int:
        """ReadAS / ReadAD prefix: u16 byte count; returns element count."""
        n = self.u16()
        if n % elem_size:
            raise FormatError(f"{self.where}: array byte count {n} not a multiple of {elem_size} at {self.pos}")
        return n // elem_size

    def array(self, kind: str) -> list[Any]:
        size = struct.calcsize(FMT[kind])
        return [self.num(kind) for _ in range(self.counted(size))]

    def command_list(self) -> list[str]:
        """ReadCommandsList: s32 count then that many _ReadSS strings."""
        n = self.s32()
        return [self.sd() for _ in range(n)]


@dataclass
class Options:
    include_secrets: bool = False
    strict: bool = False
    warnings: list[str] = field(default_factory=list)

    def warn(self, msg: str) -> None:
        if self.strict:
            raise FormatError(msg)
        self.warnings.append(msg)
        print(f"warning: {msg}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Saved objects (objdb.c ReadObject / ReadObjList)
# ---------------------------------------------------------------------------

def read_obj_list(r: Reader, opt: Options) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    while True:
        tag = r.u16()
        if tag == END_OF_LIST:
            return items
        if tag == OBJECT:
            items.append(read_object(r, opt))
        elif tag == SUB_OBJECT:
            if not items:
                raise FormatError(f"{r.where}: contents before any object at {r.pos}")
            items[-1]["contents"] = read_obj_list(r, opt)
        else:
            raise FormatError(f"{r.where}: unknown tag {tag} in object list at {r.pos - 2}")


def _apply_loop(r: Reader, fields: dict[int, tuple[str, Callable[[], Any]]]) -> list[dict[str, Any]]:
    """The ``while(1) { id; if 254 break; switch ... case 253: j++ }`` shape."""
    out: list[dict[str, Any]] = []
    cur: dict[str, Any] = {}
    while True:
        tag = r.u16()
        if tag == 254:
            if cur:
                out.append(cur)
            return out
        if tag == 253:
            out.append(cur)
            cur = {}
            continue
        if tag not in fields:
            raise FormatError(f"{r.where}: unknown apply tag {tag} at {r.pos - 2}")
        name, fn = fields[tag]
        cur[name] = fn()


def read_object(r: Reader, opt: Options) -> dict[str, Any]:
    o: dict[str, Any] = {"vnum": None, "name": None, "short_description": None,
                         "description": None, "contents": []}
    apply_types = TABLES["apply_types"]

    def fld(name: str, key: str):
        return lambda: o.__setitem__(name, r.field(key))

    def sd(name: str):
        # An empty saved string means "use the prototype's text" (ReadObject
        # copies it from the object database); null says that more honestly.
        return lambda: o.__setitem__(name, r.sd() or None)

    def value_array():
        o["value"] = r.array("s32")

    def old_apply():
        n = r.counted(LAYOUT["sizeof.old_obj_affected_type"]["size"])
        for _ in range(n):
            loc = r.u8(); r.raw(3); mod = r.s32()
            o.setdefault("apply", []).append({"location": name_at(apply_types, loc), "modifier": mod})

    def apply27():
        n = r.u8()
        for _ in range(n):
            loc = r.u8()
            mod = r.field("o.apply[0].modifier")
            o.setdefault("apply", []).append({"location": name_at(apply_types, loc), "modifier": mod})

    def apply62():
        rows = _apply_loop(r, {
            1: ("location", lambda: name_at(apply_types, r.field("o.apply[0].location"))),
            2: ("modifier", lambda: r.field("o.apply[0].modifier")),
            3: ("qualifier", lambda: r.field("o.apply[0].qualifier")),
        })
        o.setdefault("apply", []).extend(rows)

    def apply74():
        o["pulse_apply"] = _apply_loop(r, {
            1: ("location", lambda: name_at(apply_types, r.field("o.pulse_apply[0].location"))),
            2: ("modifier", lambda: r.field("o.pulse_apply[0].modifier")),
        })

    def apply83():
        o["socket_apply"] = _apply_loop(r, {
            1: ("vnum", lambda: r.field("o.socket_apply[0].vnum")),
            2: ("location", lambda: name_at(apply_types, r.field("o.socket_apply[0].location"))),
            3: ("modifier", lambda: r.field("o.socket_apply[0].modifier")),
            4: ("name", r.sd),
            5: ("identifier", lambda: r.field("o.socket_apply[0].identifier")),
            6: ("removable", lambda: r.field("o.socket_apply[0].removable")),
            7: ("unique", lambda: r.field("o.socket_apply[0].unique")),
        })

    def eq_pos():
        pos = r.field("o.eq_pos")
        o["eq_pos"] = None if pos < 0 else name_at(TABLES["wear_positions"], pos)

    def extra46():
        exs: list[dict[str, Any]] = []
        cur: dict[str, Any] | None = None
        while True:
            tag = r.u16()
            if tag == 254:
                break
            key = "keywords" if tag == 1 else "description"
            if cur is None or key in cur:
                cur = {}
                exs.append(cur)
            cur[key] = r.sd()
        o["extra_descriptions"] = exs

    handlers: dict[int, Callable[[], Any]] = {
        2: value_array,
        3: lambda: o.__setitem__("wear_flags", bits(r.field("o.wear_flags"), TABLES["wear_bits"])),
        4: lambda: o.__setitem__("extra_flags", bits(r.field("o.extra_flags"), TABLES["extra_bits"])),
        5: fld("intrinsic_weight", "o.intrinsic_weight"),
        6: fld("cost", "o.cost"),
        7: fld("cost_per_day", "o.cost_per_day"),
        8: fld("timer", "o.timer"),
        9: lambda: o.__setitem__("affects", ext_bits(list(struct.unpack("<8I", r.raw(32))), TABLES["affected_bits"])),
        10: fld("xtra_bits", "o.xtra_bits"),
        12: sd("name"), 13: sd("description"), 14: sd("short_description"), 15: sd("action_description"),
        16: eq_pos,
        17: fld("in_room", "o.in_room"),
        18: lambda: o.__setitem__("type", name_at(TABLES["item_types"], r.field("o.type_flag"))),
        19: fld("vnum", "o.vnum"),
        20: old_apply,
        21: fld("min_level", "o.min_level"),
        22: fld("time_stamp", "o.time_stamp"),
        23: lambda: r.s32(),
        24: fld("intrinsic_volume", "o.intrinsic_volume"),
        25: lambda: o.__setitem__("material", name_at(TABLES["material_types"], r.field("o.material"))),
        26: fld("length", "o.length"), 30: fld("width", "o.width"), 31: fld("height", "o.height"),
        27: apply27,
        28: fld("real_cost", "o.real_cost"),
        29: fld("timer2", "o.timer2"),
        32: fld("contents_volume", "o.contents_volume"),
        33: fld("contents_weight", "o.contents_weight"),
        34: sd("msg_to_room"), 35: sd("msg_to_char"), 36: sd("msg_to_dest"),
        37: fld("touch_to_room", "o.touch_to_room"),
        46: extra46,
        59: sd("owner"), 60: sd("held_for"),
        61: lambda: o.__setitem__("rarity", name_at(TABLES["rarity_types"], r.field("o.rarity"))),
        62: apply62,
        63: fld("mutation_count", "o.mutation_count"),
        64: fld("fixed", "o.fixed"),
        65: fld("use_cooldown", "o.use_cooldown"),
        66: fld("last_use_time", "o.last_use_time"),
        67: sd("loaded_by_imm"), 68: sd("edited_by_imm"), 69: sd("mutated_by_imm"), 70: sd("stringed_by_imm"),
        71: fld("created_date", "o.created_date"),
        72: fld("ws_cooldown", "o.ws_cooldown"),
        73: fld("last_use_time", "o.last_use_time"),
        74: apply74,
        75: fld("pulse_duration", "o.pulse_duration"),
        76: sd("pulse_finish_msg"),
        77: fld("item_set", "o.item_set"),
        78: sd("item_ability_desc"),
        79: fld("mm_crack_code", "o.mm_crack_code"),
        80: fld("mm_crack_attempts", "o.mm_crack_attempts"),
        81: fld("tier", "o.obj_tier"),
        82: fld("sockets", "o.sockets"),
        83: apply83,
    }
    while True:
        tag = r.u16()
        if tag == END_OF_OBJECT:
            return o
        h = handlers.get(tag)
        if h is None:
            raise FormatError(f"{r.where}: unknown object field {tag} at offset {r.pos - 2}")
        h()


# ---------------------------------------------------------------------------
# Player sub-records
# ---------------------------------------------------------------------------

def read_sub(r: Reader, end: int, fields: dict[int, tuple[str, Callable[[], Any]]], what: str) -> dict[str, Any]:
    out: dict[str, Any] = {}
    while True:
        tag = r.u16()
        if tag == end:
            return out
        if tag not in fields:
            raise FormatError(f"{r.where}: unknown tag {tag} in {what} at {r.pos - 2}")
        name, fn = fields[tag]
        out[name] = fn()


def read_affect(r: Reader) -> dict[str, Any]:
    spells = TABLES["spells"]
    rec = read_sub(r, AFFECT_END, {
        1: ("type", lambda: r.field("af.type")),
        2: ("duration", lambda: r.field("af.duration")),
        3: ("modifier", lambda: r.field("af.modifier")),
        4: ("location", lambda: name_at(TABLES["apply_types"], r.field("af.location"))),
        5: ("bitvector", lambda: ext_bits(r.field("af.bitvector") if LAYOUT["af.bitvector"]["kind"] == "other"
                                          else list(struct.unpack("<8I", r.raw(32))), TABLES["affected_bits"])),
    }, "affect")
    if "type" in rec:
        rec["type_name"] = attack_name(rec["type"])
    return rec


def read_pulse_cooldown(r: Reader) -> dict[str, Any]:
    rec = read_sub(r, PULSE_COOLDOWN_END, {
        1: ("type", lambda: r.field("pc.type")),
        2: ("cooldown_expire", lambda: r.field("pc.cooldown_expire")),
        3: ("bitvector", lambda: ext_bits(list(struct.unpack("<8I", r.raw(32))), TABLES["affected_bits"])),
    }, "pulse cooldown")
    if "type" in rec:
        rec["type_name"] = attack_name(rec["type"])
    return rec


def read_item_set_ability(r: Reader) -> dict[str, Any]:
    f = r.field
    return read_sub(r, ITEM_SET_ABILITY_END, {
        1: ("item_set", lambda: f("isa.item_set")), 2: ("set_name", r.sd),
        3: ("ability", lambda: f("isa.ability")), 4: ("last_use_time", lambda: f("isa.last_use_time")),
        5: ("last_ws_time", lambda: f("isa.last_ws_time")), 6: ("modifier", lambda: f("isa.modifier")),
        7: ("cooldown_expire", lambda: f("isa.cooldown_expire")), 8: ("bonus_level", lambda: f("isa.bonus_level")),
        9: ("use_duration", lambda: f("isa.use_duration")),
    }, "item set ability")


PULSE_FIELDS = {
    1: "type", 2: "damage_type", 3: "proc_type", 4: "initial_type", 6: "finish_type", 7: "can_stack",
    8: "stack_multiplier", 9: "stack_counter", 10: "start_time", 11: "last_update", 12: "pulse_message",
    13: "initial_message", 14: "finish_message", 15: "pulse_proc_delay", 16: "pulse_proc_frequency",
    17: "duration", 18: "proc_counter", 19: "total_procs", 20: "location", 21: "location_initial",
    22: "location_finish", 23: "modifier", 24: "modifier_initial", 25: "modifier_finish", 26: "caster",
    27: "is_npc", 28: "total_dam", 29: "total_heal", 30: "total_length", 31: "cooldown", 32: "total_hp_victim",
    33: "finishing_spell", 34: "finishing_spell_stack_limit", 35: "finishing_proc_stack_limit",
    36: "finish_on_caster", 37: "reset_timer_on_hit", 38: "finish_spell_lvl_limit", 39: "finish_spell_remort_limit",
    40: "can_stack_initial", 41: "stack_counter_initial", 42: "stack_multiplier_initial", 43: "initial_dam_aoe",
    44: "pulse_dam_aoe", 45: "finish_dam_aoe", 46: "total_dam_aoe", 47: "aoe_dam_multiplier",
    48: "aoe_dam_multiplier_initial", 49: "aoe_dam_multiplier_finish", 50: "is_item_set_ability",
    51: "is_item_ability", 52: "no_msg", 53: "proc_modifier_cap", 54: "bitvector", 55: "finish_aoe_dam_as_target",
    56: "initial_aoe_dam_as_target", 57: "pulse_aoe_dam_as_target", 58: "immune_dispel_magic", 59: "initial_modifier_cap",
}
PULSE_STRINGS = {"pulse_message", "initial_message", "finish_message", "caster"}


def read_pulse_affect(r: Reader) -> dict[str, Any]:
    fields: dict[int, tuple[str, Callable[[], Any]]] = {}
    for tag, name in PULSE_FIELDS.items():
        if name in PULSE_STRINGS:
            fields[tag] = (name, r.sd)
        elif name == "bitvector":
            fields[tag] = (name, lambda: ext_bits(list(struct.unpack("<8I", r.raw(32))), TABLES["affected_bits"]))
        else:
            fields[tag] = (name, (lambda k: lambda: r.field(k))(f"pa.{name}"))
    rec = read_sub(r, PULSE_AFFECT_END, fields, "pulse affect")
    if "type" in rec:
        rec["type_name"] = attack_name(rec["type"])
    if "damage_type" in rec:
        rec["damage_type"] = attack_type(rec["damage_type"])
    for k in ("proc_type", "initial_type", "finish_type"):
        if k in rec:
            rec[k] = name_at(TABLES["pulse_types"], rec[k])
    for k in ("location", "location_initial", "location_finish"):
        if k in rec:
            rec[k] = name_at(TABLES["apply_types"], rec[k])
    return rec


# ---------------------------------------------------------------------------
# Player record (player.save.c load_char_with_path)
# ---------------------------------------------------------------------------

STAT_IDS = {14: "strength", 16: "intelligence", 17: "wisdom", 18: "dexterity", 19: "constitution",
            67: "charisma", 68: "luck"}
CUR_STAT_IDS = {20: "strength", 22: "intelligence", 23: "wisdom", 24: "dexterity", 25: "constitution",
                69: "charisma", 70: "luck"}


def new_player(source: str) -> dict[str, Any]:
    return {
        "name": None, "source": source, "file_version": 0, "account_name": None, "account": None,
        "sex": None, "class": None, "race": None, "level": None, "max_level": None, "remort_count": None,
        "title": None, "shortdesc": None, "longdesc": None, "description": None, "namelist": None,
        "full_name": None, "email": None, "plan": None, "prompt": None,
        "base_stats": {}, "stats": {},
        "hit": None, "max_hit": None, "mana": None, "max_mana": None, "move": None, "max_move": None,
        "power": None, "max_power": None, "rage": None, "energy": None, "hit_shield": None,
        "gold": None, "bankgold": None, "exp": None, "apex_exp": None, "questpoints": None,
        "alignment": None, "base_alignment": None, "position": None, "act": [], "config": [],
        "log": [], "affected_by": [], "resist": [], "immune": [], "susceptible": [],
        "hit_bonus": None, "dam_bonus": None, "attacks_per_round": None, "assassinate": None,
        "armor": None, "base_armor": None, "stopping": None, "base_stopping": None, "apply_saving_throw": None,
        "conditions": None, "fullness": None, "weight": None, "height": None,
        "bindpoint": None, "was_in_room": None, "worldzone": None, "offset": None,
        "build_lo": None, "build_hi": None, "test_lo": None, "test_hi": None,
        "clan": None, "clan_rank": None, "invis_level": None, "whimpy_level": None,
        "spells_to_learn": None, "skills": [], "spells": [], "remort_bonuses": [], "kills": [],
        "affects": [], "pulse_affects": [], "pulse_cooldowns": [], "item_set_abilities": [],
        "granted": [], "revoked": [], "mail": [],
        "time": {}, "first_login": None, "last_site": None, "lockout_till": None, "lockout_message": None,
        "new_notes": None, "page_size": None, "page_width": None, "page_min_width": None,
        "rent_disable": None, "carry_weight": None, "carry_volume": None, "carry_items": None, "timer": None,
        "equipment": {}, "inventory": [], "warehouse": [],
    }


def read_player(data: bytes, source: str, opt: Options) -> dict[str, Any]:
    r = Reader(data, source)
    p = new_player(source)
    f = r.field

    def setf(name: str, key: str):
        return lambda: p.__setitem__(name, f(key))

    def sets(name: str):
        return lambda: p.__setitem__(name, r.sd())

    def settime(name: str):
        return lambda: p["time"].__setitem__(name, r.time32())

    def skills_list(target: str, table: list[str]):
        def fn():
            n = r.counted(4)
            for _ in range(n):
                num, learned = r.num("u16"), r.num("s16")
                p[target].append(skill_entry(num, learned, table))
        return fn

    def remorts():
        n = r.counted(LAYOUT["sizeof.remort_data"]["size"])
        for _ in range(n):
            flag, count, mod, bonus = struct.unpack("<iiii", r.raw(16))
            p["remort_bonuses"].append({"remort_flag": flag, "remort_count": count,
                                        "stat_modifier": mod, "stat_bonus": bonus})

    def kills():
        n = r.counted(LAYOUT["sizeof.kill_info"]["size"])
        for _ in range(n):
            vnum, nk = struct.unpack("<IH2x", r.raw(8))
            if vnum or nk:
                p["kills"].append({"vnum": vnum, "count": nk})

    def affected_array():
        size = LAYOUT["sizeof.affected_type"]["size"]
        n = r.counted(size)
        for _ in range(n):
            chunk = r.raw(size)
            typ, dur, mod, loc = struct.unpack_from("<IiiB", chunk, 0)
            words = list(struct.unpack_from("<8I", chunk, 16))
            p["affects"].append({"type": typ, "type_name": attack_name(typ), "duration": dur, "modifier": mod,
                                 "location": name_at(TABLES["apply_types"], loc),
                                 "bitvector": ext_bits(words, TABLES["affected_bits"])})

    def old_cmd_list(target: str):
        def fn():
            vals = r.array("s32")   # server discards these (numeric ids from an older build)
            if vals:
                p.setdefault("legacy_" + target, vals)
        return fn

    def objlist_after_marker(target: str):
        def fn():
            r.u16()   # SUB_OBJECT
            p[target] = read_obj_list(r, opt)
        return fn

    def wear():
        pos = r.u16()
        r.u16()   # SUB_OBJECT
        items = read_obj_list(r, opt)
        slot = name_at(TABLES["wear_positions"], pos)
        p["equipment"][str(slot)] = items[0] if len(items) == 1 else items

    def mail():
        r.u16()
        p["mail"].append(r.sd())

    handlers: dict[int, Callable[[], Any]] = {
        VERSION_MARKER: lambda: p.__setitem__("file_version", r.s32()),
        1: lambda: p.__setitem__("sex", name_at(TABLES["sexes"], f("ch.sex"))),
        2: lambda: p.__setitem__("class", name_at(TABLES["class_list"], r.u8())),
        3: sets("name"), 4: sets("shortdesc"), 5: sets("longdesc"), 6: sets("description"), 7: sets("title"),
        8: setf("level", "ch.level"), 9: setf("bindpoint", "ch.bindpoint"), 12: setf("max_level", "ch.max_level"),
        26: setf("mana", "ch.mana"), 27: setf("max_mana", "ch.max_mana"), 28: setf("hit", "ch.hit"),
        29: setf("max_hit", "ch.max_hit"), 30: setf("move", "ch.move"), 31: setf("max_move", "ch.max_move"),
        32: lambda: p.__setitem__("armor_legacy", r.num(LAYOUT["ch.armor"]["kind"])),
        33: setf("gold", "ch.gold"), 34: setf("bankgold", "ch.bankgold"), 35: setf("exp", "ch.exp"),
        38: lambda: p.__setitem__("resist", bits(f("ch.M_resist"), TABLES["immunity_names"])),
        39: lambda: p.__setitem__("immune", bits(f("ch.M_immune"), TABLES["immunity_names"])),
        40: lambda: p.__setitem__("susceptible", bits(f("ch.susc"), TABLES["immunity_names"])),
        41: lambda: p.__setitem__("attacks_per_round", r.s32()),
        42: lambda: p.__setitem__("affected_by", ext_bits(f("ch.affected_by"), TABLES["affected_bits"])),
        43: lambda: p.__setitem__("position", name_at(TABLES["position_types"], f("ch.position"))),
        44: lambda: p.__setitem__("act", bits(f("ch.act"), TABLES["player_bits"])),
        45: setf("spells_to_learn", "ch.spells_to_learn"),
        46: setf("carry_weight", "ch.carry_weight"), 47: setf("carry_items", "ch.carry_items"),
        48: setf("timer", "ch.timer"), 49: setf("was_in_room", "ch.was_in_room"),
        50: lambda: p.__setitem__("apply_saving_throw", r.array(LAYOUT["ch.apply_saving_throw"]["kind"])),
        51: lambda: p.__setitem__("conditions", r.array(LAYOUT["ch.conditions"]["kind"])),
        52: setf("invis_level", "ch.invis_level"),
        54: affected_array,
        55: lambda: p.__setitem__("race", name_at(TABLES["race_list"], f("ch.race"))),
        56: lambda: p.__setitem__("pw", r.sd()),
        57: setf("base_alignment", "ch.base_alignment"), 58: setf("whimpy_level", "ch.whimpy_level"),
        60: setf("alignment", "ch.alignment"), 61: setf("build_lo", "ch.build_lo"), 62: setf("build_hi", "ch.build_hi"),
        63: sets("prompt"),
        64: lambda: p.__setitem__("armor", r.array(LAYOUT["ch.armor"]["kind"])),
        65: lambda: p.__setitem__("stopping", r.array(LAYOUT["ch.stopping"]["kind"])),
        66: setf("clan", "ch.clan"),
        71: lambda: p.__setitem__("weight", r.num("s16")),
        72: lambda: p.__setitem__("height", r.num("s16")),
        73: lambda: None,
        74: kills,
        75: setf("hit_bonus", "ch.hit_bonus"), 76: setf("dam_bonus", "ch.dam_bonus"),
        77: lambda: r.raw(4), 78: lambda: r.raw(4), 79: lambda: None, 80: lambda: None,
        81: setf("offset", "ch.offset"),
        82: skills_list("skills", TABLES["skills"]),
        83: skills_list("spells", TABLES["spells"]),
        84: sets("email"), 85: lambda: p.__setitem__("log", bits(f("ch.log_bits"), TABLES["log_bits"])),
        86: objlist_after_marker("warehouse"),
        87: setf("carry_weight", "ch.carry_weight"), 88: setf("carry_volume", "ch.carry_volume"),
        89: setf("power", "ch.power"), 90: setf("max_power", "ch.max_power"),
        91: settime("birth"), 92: settime("logon"), 93: settime("motd"), 94: settime("password"), 95: settime("played"),
        96: sets("full_name"), 97: sets("plan"), 98: sets("last_site"),
        99: old_cmd_list("granted"), 100: old_cmd_list("revoked"),
        101: setf("new_notes", "ch.new_notes"), 102: setf("page_size", "ch.page_size"),
        103: setf("page_width", "ch.page_width"), 104: setf("account", "ch.account"),
        105: setf("page_min_width", "ch.page_min_width"), 106: setf("lockout_till", "ch.lockout_till"),
        107: sets("lockout_message"), 108: sets("account_name"), 109: settime("logout"),
        110: setf("fullness", "ch.fullness"), 111: setf("rent_disable", "ch.rent_disable"),
        112: lambda: p.__setitem__("granted", r.command_list()),
        113: lambda: p.__setitem__("revoked", r.command_list()),
        114: setf("weight", "ch.weight"), 115: setf("height", "ch.height"),
        116: setf("questpoints", "ch.questpoints"), 117: setf("worldzone", "ch.worldzone"),
        118: lambda: p.__setitem__("config", bits(f("ch.config_bits"), TABLES["config_bits"])),
        119: setf("remort_count", "ch.remort_count"),
        120: lambda: p.__setitem__("clan_rank", name_at(TABLES["clan_ranks"], f("ch.clan_rank"))), 121: setf("test_lo", "ch.test_lo"), 122: setf("test_hi", "ch.test_hi"),
        123: lambda: p.__setitem__("base_armor", r.array(LAYOUT["ch.base_armor"]["kind"])),
        124: lambda: p.__setitem__("base_stopping", r.array(LAYOUT["ch.base_stopping"]["kind"])),
        125: setf("attacks_per_round", "ch.attacks_per_round"),
        126: lambda: p.__setitem__("class", name_at(TABLES["class_list"], f("ch.job"))),
        127: sets("namelist"), 128: lambda: p.__setitem__("first_login", r.time32()),
        129: remorts,
        130: setf("apex_exp", "ch.apex_exp"), 131: setf("hit_shield", "ch.hit_shield"),
        132: setf("assassinate", "ch.assassinate"), 133: setf("rage", "ch.rage"), 134: setf("energy", "ch.energy"),
        MAIL: mail,
        PULSE_AFFECT: lambda: p["pulse_affects"].append(read_pulse_affect(r)),
        PULSE_COOLDOWN: lambda: p["pulse_cooldowns"].append(read_pulse_cooldown(r)),
        ITEM_SET_ABILITY: lambda: p["item_set_abilities"].append(read_item_set_ability(r)),
        AFFECT: lambda: p["affects"].append(read_affect(r)),
        WEAR: wear,
        SUB_OBJECT: lambda: p.__setitem__("inventory", read_obj_list(r, opt)),
    }
    for tag, name in STAT_IDS.items():
        handlers[tag] = (lambda n, k: lambda: p["base_stats"].__setitem__(n, f(k)))(name, f"ch.base_stats.{name}")
    for tag, name in CUR_STAT_IDS.items():
        handlers[tag] = (lambda n, k: lambda: p["stats"].__setitem__(n, f(k)))(name, f"ch.stats.{name}")

    while True:
        if r.eof():
            opt.warn(f"{source}: file ends without EOF marker")
            break
        tag = r.u16()
        if tag == EOF_MARK:
            break
        h = handlers.get(tag)
        if h is None:
            raise FormatError(f"{source}: unknown load type {tag} at offset {r.pos - 2}")
        h()
    if r.pos < len(r.d):
        opt.warn(f"{source}: {len(r.d) - r.pos} trailing bytes after EOF marker")

    finish_char(p, opt)
    if not opt.include_secrets:
        p.pop("pw", None)
    return p


def finish_char(p: dict[str, Any], opt: Options) -> None:
    """The version upgrades in player.save.c finish_char, so every record has
    current (version 6) semantics."""
    v = p["file_version"]
    if v > CURRENT_PLAYER_FILE_VERSION:
        opt.warn(f"{p['source']}: unknown player file version {v}")
        return
    if v <= 0:
        if p["weight"] is not None:
            p["weight"] = p["weight"] * 100          # POUNDS_TO_DECIM
        if p["height"] is not None:
            p["height"] = (p["height"] * 10) // 13   # CM_TO_GOBITS
    if v <= 2:
        wimpy = name_at(TABLES["player_bits"], 4)
        if wimpy in p["act"]:
            p["whimpy_level"] = (p["hit"] or 0) // 5
            p["act"].remove(wimpy)
    if v <= 5:
        # clan 1 ("Protected") min_join_level is 20 in clans.current
        if (p["level"] or 0) > 20:
            p["clan"] = 1
        corrupt = name_at(TABLES["player_bits"], 24)
        if corrupt in p["act"]:
            p["act"].remove(corrupt)
            p["clan"] = 2
    if p["name"]:
        p["name"] = p["name"][0].upper() + p["name"][1:].lower()
    if not p["namelist"] and p["name"]:
        p["namelist"] = p["name"].lower()


# ---------------------------------------------------------------------------
# Account record (account.c load_acct)
# ---------------------------------------------------------------------------

def read_account(data: bytes, source: str, opt: Options) -> dict[str, Any]:
    r = Reader(data, source)
    a: dict[str, Any] = {
        "name": None, "source": source, "real_name": None, "maiden_name": None, "email_address": None,
        "characters": [], "account": None, "flags": [], "term_type_id": None,
        "last_site": None, "last_site1": None, "last_site2": None, "last_site3": None,
        "last_login": None, "last_logout": None, "motd": None, "vote_time": None,
        "last_roll_start": None, "num_rolls": None, "last_class_char": None,
        "granted": [], "revoked": [], "notes": None, "ignore_list": [], "warehouse": [],
    }

    def chars():
        n = r.field("a.num_chars")
        a["characters"] = [r.sd() for _ in range(n)]

    def ignores():
        n = r.field("a.num_ignore")
        a["ignore_list"] = [r.sd() for _ in range(n)]

    def warehouse():
        r.u16()
        a["warehouse"] = read_obj_list(r, opt)

    handlers: dict[int, Callable[[], Any]] = {
        1: lambda: a.__setitem__("name", r.sd()), 2: lambda: a.__setitem__("pw", r.sd()),
        3: lambda: a.__setitem__("maiden_name", r.sd()), 4: lambda: a.__setitem__("email_address", r.sd()),
        5: lambda: a.__setitem__("account", r.field("a.account")),
        6: lambda: a.__setitem__("term_type_id", r.field("a.term_type_id")),
        7: chars,
        8: lambda: a.__setitem__("flags", bits(r.field("a.flags"), TABLES["account_bits"])),
        9: lambda: a.__setitem__("real_name", r.sd()),
        10: lambda: a.__setitem__("motd", r.time32()),
        11: lambda: a.__setitem__("last_site", r.sd()),
        12: lambda: a.__setitem__("last_login", r.time32()),
        13: lambda: a.__setitem__("last_logout", r.time32()),
        14: lambda: a.__setitem__("granted", r.command_list()),
        15: lambda: a.__setitem__("revoked", r.command_list()),
        16: lambda: a.__setitem__("notes", r.sd()),
        17: ignores,
        18: lambda: a.__setitem__("last_roll_start", r.field("a.last_roll_start")),
        19: lambda: a.__setitem__("num_rolls", r.field("a.num_rolls")),
        20: lambda: a.__setitem__("last_class_char", r.field("a.last_class_char")),
        21: lambda: a.__setitem__("last_site1", r.sd()), 22: lambda: a.__setitem__("last_site2", r.sd()),
        23: lambda: a.__setitem__("last_site3", r.sd()),
        24: lambda: a.__setitem__("vote_time", r.time32()),
        25: warehouse,
    }
    while True:
        if r.eof():
            opt.warn(f"{source}: file ends without EOF marker")
            break
        tag = r.u16()
        if tag == EOF_MARK:
            break
        if tag == VERSION_MARKER and r.pos == 2:
            raise FormatError(f"{source}: this is a player file (starts with the player version marker), not an account; skipped")
        h = handlers.get(tag)
        if h is None:
            raise FormatError(f"{source}: unknown account load type {tag} at offset {r.pos - 2}")
        h()
    if not opt.include_secrets:
        a.pop("pw", None)
    return a


# ---------------------------------------------------------------------------
# Sources: a .tar backup or an extracted directory
# ---------------------------------------------------------------------------

def iter_files(src: Path, subdir: str) -> Iterator[tuple[str, bytes]]:
    """Yield (relative path, bytes) for every file under ``subdir/<letter>/``."""
    if src.is_dir():
        base = src / subdir
        for letter in sorted(p for p in base.iterdir() if p.is_dir()) if base.is_dir() else []:
            for f in sorted(p for p in letter.iterdir() if p.is_file()):
                yield f"{subdir}/{letter.name}/{f.name}", f.read_bytes()
        return
    with tarfile.open(src) as tar:
        for m in sorted(tar.getmembers(), key=lambda m: m.name):
            parts = m.name.split("/")
            if m.isfile() and len(parts) == 3 and parts[0] == subdir:
                fh = tar.extractfile(m)
                if fh is not None:
                    yield m.name, fh.read()


def convert_players(src: Path, opt: Options) -> list[dict[str, Any]]:
    out = []
    for rel, data in iter_files(src, "stash"):
        try:
            out.append(read_player(data, rel, opt))
        except FormatError as e:
            opt.warn(str(e))
    return out


def convert_accounts(src: Path, opt: Options) -> list[dict[str, Any]]:
    out = []
    for rel, data in iter_files(src, "account"):
        try:
            out.append(read_account(data, rel, opt))
        except FormatError as e:
            opt.warn(str(e))
    return out
