"""Generate src/names.py: the game's fixed vocabularies as enums.

Source is py_json/src/prworld/names.json (itself extracted from the C name
tables by py_json/tools/gen_names.py). Run from py-pr:

    uv run python tools/gen_enums.py

Code tables (sex, position, item kind ...) become ``CodedStrEnum`` classes:
the value is the string exactly as the game spells it, which is what the
JSONL carries, and each member also carries the numeric code (table index).

Bit tables (room flags, affect bits, immunities ...) become ``CodedFlag``
classes, ``enum.Flag`` subclasses: one member per bit, so a field holding a
set of them is one integer and membership, any-of and all-of tests are single
AND operations. Each member carries the game's ``label`` string and its bit
``code``; the list of labels the JSONL carries is converted at the model
boundary (``from_names`` / ``names``), which pydantic does automatically.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
NAMES = HERE.parent / "py_json" / "src" / "prworld" / "names.json"
OUT = HERE / "src" / "names.py"

# enum class name -> (table, one-line description)
ENUMS = {
    "Direction": ("dirs", "Exit direction; code is the exit array index (dirs[])."),
    "Sex": ("sexes", "Character sex (sexes[])."),
    "Position": ("position_types", "Character position, from dead to standing (position_types[])."),
    "Rarity": ("rarity_types", "Object rarity tier (rarity_types[])."),
    "Material": ("material_types", "What an object is made of (material_types[])."),
    "WeaponClass": ("weapon_types", "Weapon proficiency class (weapon_types[])."),
    "DamageType": ("damage_types", "Weapon damage type (damage_types[])."),
    "Drink": ("drinks", "Liquid in a drink container (drinks[])."),
    "ItemKind": ("item_types", "Object type name as the server prints it (item_types[])."),
    "RaceName": ("race_list", "Race by name; code is the race vnum (race_list[])."),
    "ClassName": ("class_list", "Character/mob class name (class_list[])."),
    "RoomFlag": ("room_bits", "Room flag (room_bits[])."),
    "ExitFlag": ("exit_bits", "Door/exit flag (exit_bits[])."),
    "ContainerFlag": ("container_bits", "Container state flag (container_bits[])."),
    "BoardFlag": ("board_bits", "Bulletin board permission flag (board_bits[])."),
    "WearFlag": ("wear_bits", "Where an object can be worn (wear_bits[])."),
    "ObjectFlag": ("extra_bits", "Object extra flag: glow, hum, magic, cursed ... (extra_bits[])."),
    "MobAction": ("action_bits", "Mob behaviour flag (action_bits[])."),
    "AffectBit": ("affected_bits", "Spell affect bit on a character or granted by an object (affected_bits[])."),
    "Immunity": ("immunity_names", "Damage class for immune/resistant/susceptible (immunity_names[])."),
    "SectorFlag": ("sector_bits", "Sector flag (sector_bits[])."),
    "ClanFlag": ("clan_flags", "Clan flag (clan_flags[])."),
    "TrapEffect": ("trap_eff_flags", "Trap effect flag (trap_eff_flags[])."),
    "PlayerFlag": ("player_bits", "Player act flag (player_bits[])."),
    "AccountFlag": ("account_bits", "Account flag (account_bits[])."),
    "Form": ("forms", "Body form of a race (forms[])."),
    "Intrinsic": ("intrinsics", "Racial intrinsic ability (intrinsics[])."),
    "ApplyLocation": ("apply_types", "What an apply modifies (apply_types[])."),
    "PulseType": ("pulse_types", "What a pulse affect does on each pulse (PULSE_TYPE_*)."),
    "WearPosition": ("wear_positions", "Equipment slot (WEAR_* / WIELD / HOLD / POUCH), code 0..21."),
    "ConfigFlag": ("config_bits", "Player display/behaviour preference (CONFIG_*)."),
    "LogFlag": ("log_bits", "Server log channel (LOG_*)."),
    "ClanRank": ("clan_ranks", "Rank within a clan (clan_ranks[])."),
}

# The tables that are bit vectors in C (a u32, or u32[8] for affected_bits).
# These become CodedFlag classes; everything else is a CodedStrEnum.
FLAGS = {
    "RoomFlag", "ExitFlag", "ContainerFlag", "BoardFlag", "WearFlag", "ObjectFlag", "MobAction",
    "AffectBit", "Immunity", "SectorFlag", "ClanFlag", "TrapEffect", "PlayerFlag", "AccountFlag",
    "Form", "Intrinsic", "ConfigFlag", "LogFlag",
}

# Member names for bits whose C table entry is not usable as-is. The label
# (what the JSONL carries) stays the table string.
MEMBER_NAMES = {
    # action_bits[] lists "polymorphed" twice; the defines are ACT_POLYSELF (14)
    # and ACT_POLYOTHER (15). Both bits occur in the data, so both are members.
    ("MobAction", 14): "polymorphed_self",
    ("MobAction", 15): "polymorphed_other",
}

HEADER = '''"""Fixed vocabularies of the game as enums. GENERATED by tools/gen_enums.py
from the C name tables; do not edit by hand.

Code tables are ``CodedStrEnum`` classes: each member's value is the string
the game uses (and the JSONL carries); its ``code`` is the numeric code in
the C table. Convert with ``member.code`` and ``Enum.from_code(n)``.

Bit tables are ``CodedFlag`` classes (``enum.Flag``): a set of flags is one
integer, so ``Flag.x in flags``, ``flags & (Flag.x | Flag.y)`` and
``flags & wanted == wanted`` are single AND operations. Each member has the
game's ``label`` string and its bit ``code``. The JSONL's list of labels is
the boundary form: ``Flag.from_names([...])`` in, ``flags.names`` out, and
pydantic applies both. ``from_bits`` / ``to_bits`` handle a 32-bit C word and
``from_words`` / ``to_words`` a u32[8] extended bitvector.
"""

from __future__ import annotations

from enum import EnumType, Flag, StrEnum
from typing import Any, Iterable

_FAST_OPS = ("__and__", "__or__", "__xor__", "__rand__", "__ror__", "__rxor__")


class _CodedFlagType(EnumType):
    """EnumType re-installs Flag's own & | ^ on every Flag subclass it builds,
    which would hide CodedFlag's fast versions; put them back."""

    def __new__(mcls, name, bases, classdict, **kwds):
        cls = super().__new__(mcls, name, bases, classdict, **kwds)
        for op in _FAST_OPS:
            for base in cls.__mro__[1:]:
                if base is Flag:
                    break
                if op in base.__dict__ and base.__dict__[op] is not getattr(Flag, op):
                    setattr(cls, op, base.__dict__[op])
                    break
        return cls


class CodedFlag(Flag, metaclass=_CodedFlagType):
    """A flag set over the game's bits; members carry ``label`` (the game's
    string for the bit) and ``code`` (the bit index)."""

    label: str
    code: int

    def __new__(cls, code: int, label: str):
        obj = object.__new__(cls)
        obj._value_ = 1 << code
        obj.code = code
        obj.label = label
        return obj

    # enum.Flag builds every result of & | ^ through the class call, about a
    # microsecond each. Results are cached in _value2member_map_, so after the
    # first time a plain dict lookup returns the same object; only a new
    # combination takes the slow path.

    def __and__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ & other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__and__(self, other)

    def __or__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ | other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__or__(self, other)

    def __xor__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ ^ other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__xor__(self, other)

    __rand__ = __and__
    __ror__ = __or__
    __rxor__ = __xor__

    def has_any(self, other) -> bool:
        """True if any bit of ``other`` is set: the C ``IS_SET(flags, A|B)``."""
        return bool(self._value_ & other._value_)

    def has_all(self, other) -> bool:
        """True if every bit of ``other`` is set."""
        return self._value_ & other._value_ == other._value_

    @classmethod
    def _labels(cls) -> dict[str, CodedFlag]:
        by_label = cls.__dict__.get("_by_label_")
        if by_label is None:
            by_label = {}
            for m in cls:
                by_label.setdefault(m.label, m)   # a repeated label resolves to its first bit
            setattr(cls, "_by_label_", by_label)
        return by_label

    @classmethod
    def from_names(cls, names: Iterable[str]):
        """Flag set from the game's label strings (the JSONL form)."""
        by_label = cls._labels()
        value = 0
        for name in names:
            try:
                value |= by_label[name]._value_
            except KeyError:
                raise ValueError(f"{cls.__name__}: no flag named {name!r}") from None
        return cls(value)

    @property
    def names(self) -> list[str]:
        """The game's label strings for the set bits, in bit order (the JSONL form)."""
        return [m.label for m in self]

    @classmethod
    def from_code(cls, code: int):
        """Member for a bit index."""
        for m in cls:
            if m.code == code:
                return m
        raise ValueError(f"{cls.__name__}: no member with code {code}")

    @classmethod
    def from_bits(cls, word: int):
        """Flag set from a 32-bit C flag word; bits the table does not name are dropped."""
        value = 0
        for m in cls:
            if m.code < 32 and word >> m.code & 1:
                value |= m._value_
        return cls(value)

    @classmethod
    def from_words(cls, words: Iterable[int]):
        """Flag set from a u32[n] extended bitvector."""
        words = list(words)
        value = 0
        for m in cls:
            if m.code // 32 < len(words) and words[m.code // 32] >> (m.code % 32) & 1:
                value |= m._value_
        return cls(value)

    def to_bits(self) -> int:
        """32-bit C flag word (codes above 31 need to_words)."""
        return sum(1 << m.code for m in self)

    def to_words(self, n: int = 8) -> list[int]:
        """u32[n] extended bitvector."""
        words = [0] * n
        for m in self:
            words[m.code // 32] |= 1 << (m.code % 32)
        return words

    @classmethod
    def __get_pydantic_core_schema__(cls, source: Any, handler: Any):
        """Validate from a list of labels (or one label, or an instance);
        serialise to the list of labels. Keeps the JSONL form at the boundary."""
        from pydantic_core import core_schema

        def validate(v: Any):
            if isinstance(v, cls):
                return v
            if isinstance(v, str):
                return cls.from_names([v])
            if isinstance(v, (list, tuple, set, frozenset)):
                return cls.from_names(v)
            raise ValueError(f"{cls.__name__}: expected a list of flag names, got {type(v).__name__}")

        return core_schema.no_info_plain_validator_function(
            validate,
            json_schema_input_schema=core_schema.list_schema(core_schema.str_schema()),
            serialization=core_schema.plain_serializer_function_ser_schema(lambda f: f.names),
        )


class CodedStrEnum(StrEnum):
    """A StrEnum whose members also carry the game's numeric code."""

    code: int

    def __new__(cls, value: str, code: int):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.code = code
        return obj

    @classmethod
    def from_code(cls, code: int):
        """Member for a numeric code (codes of duplicated names resolve too)."""
        for m in cls:
            if m.code == code:
                return m
        name = _ALIAS_CODES.get(cls, {}).get(code)
        if name is not None:
            return cls(name)
        raise ValueError(f"{cls.__name__}: no member with code {code}")


# codes whose name duplicates an earlier member's (a few C tables repeat names)
_ALIAS_CODES: dict[type, dict[int, str]] = {}

'''

RESERVED = {"none", "class", "def", "from", "import", "in", "is", "not", "or", "and", "if", "else",
            "min", "max", "map", "code"}


def ident(value: str, used: set[str]) -> str:
    name = re.sub(r"[^0-9a-zA-Z]+", "_", value).strip("_").lower()
    if not name:
        name = "blank"
    if name[0].isdigit():
        name = "n" + name
    if name in RESERVED:
        name += "_"
    base, i = name, 2
    while name in used:
        name = f"{base}_{i}"
        i += 1
    used.add(name)
    return name


def main() -> None:
    tables = json.loads(NAMES.read_text(encoding="utf-8"))["tables"]
    out = [HEADER]
    alias_lines = []
    for cls, (table, doc) in ENUMS.items():
        values = tables[table]
        is_flag = cls in FLAGS
        used: set[str] = set()
        out.append(f"\nclass {cls}({'CodedFlag' if is_flag else 'CodedStrEnum'}):")
        out.append(f'    """{doc}"""')
        out.append("")
        seen: dict[str, str] = {}
        aliases: dict[int, str] = {}
        for i, v in enumerate(values):
            if not v:
                if is_flag:
                    # A bit the C table leaves unnamed. Players still carry
                    # some of these set; the extractor spells them "bit<n>".
                    out.append(f"    bit{i} = {i}, 'bit{i}'    # no name in the C table")
                    used.add(f"bit{i}")
                else:
                    out.append(f"    # code {i} has no name in the C table")
                continue
            override = MEMBER_NAMES.get((cls, i))
            if is_flag:
                # Every bit is its own member; a repeated label needs a member
                # name of its own (MEMBER_NAMES), and from_names resolves the
                # label to its first bit.
                member = override or ident(v, used)
                if override:
                    used.add(member)
                note = "    # the C table repeats this name" if v in seen and not override else ""
                seen.setdefault(v, member)
                out.append(f"    {member} = {i}, {v!r}{note}")
                continue
            member = override or ident(v, used)
            if v in seen:
                out.append(f"    # code {i} is also {v!r} (see {seen[v]})")
                aliases[i] = v
                continue
            seen[v] = member
            out.append(f"    {member} = {v!r}, {i}")
        out.append("")
        if aliases:
            alias_lines.append(f"_ALIAS_CODES[{cls}] = {aliases!r}")
    out.append("")
    out.extend(alias_lines)
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(ENUMS)} enums")


if __name__ == "__main__":
    main()
