"""Generate src/names.py: StrEnum classes for the game's fixed vocabularies.

Source is py_json/src/prworld/names.json (itself extracted from the C name
tables by py_json/tools/gen_names.py). Run from py-pr:

    uv run python tools/gen_enums.py

Member names are the table strings made into identifiers; values are the
strings exactly as the game spells them, which is what the JSONL carries;
each member also carries the numeric code (table index / bit number).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
NAMES = HERE.parent / "py_json" / "src" / "prworld" / "names.json"
OUT = HERE / "src" / "names.py"

# enum class name -> (table, one-line description)
ENUMS = {
    "Direction": ("dirs", "Exit direction; code is the exit array index (dirs[])."),
    "Sex": ("sexes", "Character sex (sexes[])."),
    "Position": ("position_types", "Character position, from dead to standing (position_types[])."),
    "Rarity": ("rarity_types", "Object rarity tier (rarity_types[])."),
    "Material": ("material_types", "What an object is made of (material_types[])."),
    "WeaponClass": ("weapon_types", "Weapon proficiency class (weapon_types[])."),
    "DamageType": ("damage_types", "Weapon damage type (damage_types[])."),
    "Drink": ("drinks", "Liquid in a drink container (drinks[])."),
    "ItemKind": ("item_types", "Object type name as the server prints it (item_types[])."),
    "RaceName": ("race_list", "Race by name; code is the race vnum (race_list[])."),
    "ClassName": ("class_list", "Character/mob class name (class_list[])."),
    "RoomFlag": ("room_bits", "Room flag (room_bits[])."),
    "ExitFlag": ("exit_bits", "Door/exit flag (exit_bits[])."),
    "ContainerFlag": ("container_bits", "Container state flag (container_bits[])."),
    "BoardFlag": ("board_bits", "Bulletin board permission flag (board_bits[])."),
    "WearFlag": ("wear_bits", "Where an object can be worn (wear_bits[])."),
    "ObjectFlag": ("extra_bits", "Object extra flag: glow, hum, magic, cursed ... (extra_bits[])."),
    "MobAction": ("action_bits", "Mob behaviour flag (action_bits[])."),
    "AffectBit": ("affected_bits", "Spell affect bit on a character or granted by an object (affected_bits[])."),
    "Immunity": ("immunity_names", "Damage class for immune/resistant/susceptible (immunity_names[])."),
    "SectorFlag": ("sector_bits", "Sector flag (sector_bits[])."),
    "ClanFlag": ("clan_flags", "Clan flag (clan_flags[])."),
    "TrapEffect": ("trap_eff_flags", "Trap effect flag (trap_eff_flags[])."),
    "PlayerFlag": ("player_bits", "Player act flag (player_bits[])."),
    "AccountFlag": ("account_bits", "Account flag (account_bits[])."),
    "Form": ("forms", "Body form of a race (forms[])."),
    "Intrinsic": ("intrinsics", "Racial intrinsic ability (intrinsics[])."),
    "ApplyLocation": ("apply_types", "What an apply modifies (apply_types[])."),
    "PulseType": ("pulse_types", "What a pulse affect does on each pulse (PULSE_TYPE_*)."),
    "WearPosition": ("wear_positions", "Equipment slot (WEAR_* / WIELD / HOLD / POUCH), code 0..21."),
    "ConfigFlag": ("config_bits", "Player display/behaviour preference (CONFIG_*)."),
    "LogFlag": ("log_bits", "Server log channel (LOG_*)."),
    "ClanRank": ("clan_ranks", "Rank within a clan (clan_ranks[])."),
}

HEADER = '''"""Fixed vocabularies of the game as StrEnums. GENERATED by tools/gen_enums.py
from the C name tables; do not edit by hand.

Each member's value is the string the game uses (and the JSONL carries); its
``code`` is the numeric code or bit index in the C table. Convert with
``member.code`` and ``Enum.from_code(n)``; for flag sets ``Enum.from_bits(word)``
/ ``Enum.to_bits(members)`` handle a 32-bit word and ``from_words`` /
``to_words`` a u32[8] extended bitvector.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Iterable


class CodedStrEnum(StrEnum):
    """A StrEnum whose members also carry the game's numeric code."""

    code: int

    def __new__(cls, value: str, code: int):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.code = code
        return obj

    @classmethod
    def from_code(cls, code: int):
        """Member for a numeric code (codes of duplicated names resolve too)."""
        for m in cls:
            if m.code == code:
                return m
        name = _ALIAS_CODES.get(cls, {}).get(code)
        if name is not None:
            return cls(name)
        raise ValueError(f"{cls.__name__}: no member with code {code}")

    @classmethod
    def from_bits(cls, word: int) -> list:
        """Members whose bit is set in a 32-bit flag word."""
        return [m for m in cls if m.code < 32 and word & (1 << m.code)]

    @classmethod
    def from_words(cls, words: Iterable[int]) -> list:
        """Members set in a u32[n] extended bitvector."""
        words = list(words)
        return [m for m in cls
                if m.code // 32 < len(words) and words[m.code // 32] & (1 << (m.code % 32))]

    @classmethod
    def to_bits(cls, members: Iterable) -> int:
        """32-bit flag word from members (codes above 31 need to_words)."""
        word = 0
        for m in members:
            word |= 1 << cls(m).code
        return word

    @classmethod
    def to_words(cls, members: Iterable, n: int = 8) -> list[int]:
        """u32[n] extended bitvector from members."""
        words = [0] * n
        for m in members:
            c = cls(m).code
            words[c // 32] |= 1 << (c % 32)
        return words


# codes whose name duplicates an earlier member's (a few C tables repeat names)
_ALIAS_CODES: dict[type, dict[int, str]] = {}

'''

RESERVED = {"none", "class", "def", "from", "import", "in", "is", "not", "or", "and", "if", "else",
            "min", "max", "map", "code"}


def ident(value: str, used: set[str]) -> str:
    name = re.sub(r"[^0-9a-zA-Z]+", "_", value).strip("_").lower()
    if not name:
        name = "blank"
    if name[0].isdigit():
        name = "n" + name
    if name in RESERVED:
        name += "_"
    base, i = name, 2
    while name in used:
        name = f"{base}_{i}"
        i += 1
    used.add(name)
    return name


def main() -> None:
    tables = json.loads(NAMES.read_text(encoding="utf-8"))["tables"]
    out = [HEADER]
    alias_lines = []
    for cls, (table, doc) in ENUMS.items():
        values = tables[table]
        used: set[str] = set()
        out.append(f"\nclass {cls}(CodedStrEnum):")
        out.append(f'    """{doc}"""')
        out.append("")
        seen: dict[str, str] = {}
        aliases: dict[int, str] = {}
        for i, v in enumerate(values):
            if not v:
                out.append(f"    # code {i} has no name in the C table")
                continue
            member = ident(v, used)
            if v in seen:
                out.append(f"    # code {i} is also {v!r} (see {seen[v]})")
                aliases[i] = v
                continue
            seen[v] = member
            out.append(f"    {member} = {v!r}, {i}")
        out.append("")
        if aliases:
            alias_lines.append(f"_ALIAS_CODES[{cls}] = {aliases!r}")
    out.append("")
    out.extend(alias_lines)
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(ENUMS)} enums")


if __name__ == "__main__":
    main()
