"""Fixed vocabularies of the game as enums. GENERATED by tools/gen_enums.py
from the C name tables; do not edit by hand.

Code tables are ``CodedStrEnum`` classes: each member's value is the string
the game uses (and the JSONL carries); its ``code`` is the numeric code in
the C table. Convert with ``member.code`` and ``Enum.from_code(n)``.

Bit tables are ``CodedFlag`` classes (``enum.Flag``): a set of flags is one
integer, so ``Flag.x in flags``, ``flags & (Flag.x | Flag.y)`` and
``flags & wanted == wanted`` are single AND operations. Each member has the
game's ``label`` string and its bit ``code``. The JSONL's list of labels is
the boundary form: ``Flag.from_names([...])`` in, ``flags.names`` out, and
pydantic applies both. ``from_bits`` / ``to_bits`` handle a 32-bit C word and
``from_words`` / ``to_words`` a u32[8] extended bitvector.
"""

from __future__ import annotations

from enum import EnumType, Flag, StrEnum
from typing import Any, Iterable

_FAST_OPS = ("__and__", "__or__", "__xor__", "__rand__", "__ror__", "__rxor__")


class _CodedFlagType(EnumType):
    """EnumType re-installs Flag's own & | ^ on every Flag subclass it builds,
    which would hide CodedFlag's fast versions; put them back."""

    def __new__(mcls, name, bases, classdict, **kwds):
        cls = super().__new__(mcls, name, bases, classdict, **kwds)
        for op in _FAST_OPS:
            for base in cls.__mro__[1:]:
                if base is Flag:
                    break
                if op in base.__dict__ and base.__dict__[op] is not getattr(Flag, op):
                    setattr(cls, op, base.__dict__[op])
                    break
        return cls


class CodedFlag(Flag, metaclass=_CodedFlagType):
    """A flag set over the game's bits; members carry ``label`` (the game's
    string for the bit) and ``code`` (the bit index)."""

    label: str
    code: int

    def __new__(cls, code: int, label: str):
        obj = object.__new__(cls)
        obj._value_ = 1 << code
        obj.code = code
        obj.label = label
        return obj

    # enum.Flag builds every result of & | ^ through the class call, about a
    # microsecond each. Results are cached in _value2member_map_, so after the
    # first time a plain dict lookup returns the same object; only a new
    # combination takes the slow path.

    def __and__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ & other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__and__(self, other)

    def __or__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ | other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__or__(self, other)

    def __xor__(self, other):
        if not isinstance(other, self.__class__):
            return NotImplemented
        v = self._value_ ^ other._value_
        m = self._value2member_map_.get(v)
        return m if m is not None else Flag.__xor__(self, other)

    __rand__ = __and__
    __ror__ = __or__
    __rxor__ = __xor__

    def has_any(self, other) -> bool:
        """True if any bit of ``other`` is set: the C ``IS_SET(flags, A|B)``."""
        return bool(self._value_ & other._value_)

    def has_all(self, other) -> bool:
        """True if every bit of ``other`` is set."""
        return self._value_ & other._value_ == other._value_

    @classmethod
    def _labels(cls) -> dict[str, CodedFlag]:
        by_label = cls.__dict__.get("_by_label_")
        if by_label is None:
            by_label = {}
            for m in cls:
                by_label.setdefault(m.label, m)   # a repeated label resolves to its first bit
            setattr(cls, "_by_label_", by_label)
        return by_label

    @classmethod
    def from_names(cls, names: Iterable[str]):
        """Flag set from the game's label strings (the JSONL form)."""
        by_label = cls._labels()
        value = 0
        for name in names:
            try:
                value |= by_label[name]._value_
            except KeyError:
                raise ValueError(f"{cls.__name__}: no flag named {name!r}") from None
        return cls(value)

    @property
    def names(self) -> list[str]:
        """The game's label strings for the set bits, in bit order (the JSONL form)."""
        return [m.label for m in self]

    @classmethod
    def from_code(cls, code: int):
        """Member for a bit index."""
        for m in cls:
            if m.code == code:
                return m
        raise ValueError(f"{cls.__name__}: no member with code {code}")

    @classmethod
    def from_bits(cls, word: int):
        """Flag set from a 32-bit C flag word; bits the table does not name are dropped."""
        value = 0
        for m in cls:
            if m.code < 32 and word >> m.code & 1:
                value |= m._value_
        return cls(value)

    @classmethod
    def from_words(cls, words: Iterable[int]):
        """Flag set from a u32[n] extended bitvector."""
        words = list(words)
        value = 0
        for m in cls:
            if m.code // 32 < len(words) and words[m.code // 32] >> (m.code % 32) & 1:
                value |= m._value_
        return cls(value)

    def to_bits(self) -> int:
        """32-bit C flag word (codes above 31 need to_words)."""
        return sum(1 << m.code for m in self)

    def to_words(self, n: int = 8) -> list[int]:
        """u32[n] extended bitvector."""
        words = [0] * n
        for m in self:
            words[m.code // 32] |= 1 << (m.code % 32)
        return words

    @classmethod
    def __get_pydantic_core_schema__(cls, source: Any, handler: Any):
        """Validate from a list of labels (or one label, or an instance);
        serialise to the list of labels. Keeps the JSONL form at the boundary."""
        from pydantic_core import core_schema

        def validate(v: Any):
            if isinstance(v, cls):
                return v
            if isinstance(v, str):
                return cls.from_names([v])
            if isinstance(v, (list, tuple, set, frozenset)):
                return cls.from_names(v)
            raise ValueError(f"{cls.__name__}: expected a list of flag names, got {type(v).__name__}")

        return core_schema.no_info_plain_validator_function(
            validate,
            json_schema_input_schema=core_schema.list_schema(core_schema.str_schema()),
            serialization=core_schema.plain_serializer_function_ser_schema(lambda f: f.names),
        )


class CodedStrEnum(StrEnum):
    """A StrEnum whose members also carry the game's numeric code."""

    code: int

    def __new__(cls, value: str, code: int):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.code = code
        return obj

    @classmethod
    def from_code(cls, code: int):
        """Member for a numeric code (codes of duplicated names resolve too)."""
        for m in cls:
            if m.code == code:
                return m
        name = _ALIAS_CODES.get(cls, {}).get(code)
        if name is not None:
            return cls(name)
        raise ValueError(f"{cls.__name__}: no member with code {code}")


# codes whose name duplicates an earlier member's (a few C tables repeat names)
_ALIAS_CODES: dict[type, dict[int, str]] = {}



class Direction(CodedStrEnum):
    """Exit direction; code is the exit array index (dirs[])."""

    north = 'north', 0
    east = 'east', 1
    south = 'south', 2
    west = 'west', 3
    up = 'up', 4
    down = 'down', 5
    northeast = 'northeast', 6
    southeast = 'southeast', 7
    southwest = 'southwest', 8
    northwest = 'northwest', 9


class Sex(CodedStrEnum):
    """Character sex (sexes[])."""

    neuter = 'neuter', 0
    male = 'male', 1
    female = 'female', 2


class Position(CodedStrEnum):
    """Character position, from dead to standing (position_types[])."""

    dead = 'Dead', 0
    mortally_wounded = 'Mortally wounded', 1
    incapacitated = 'Incapacitated', 2
    stunned = 'Stunned', 3
    sleeping = 'Sleeping', 4
    resting = 'Resting', 5
    praying = 'Praying', 6
    sitting = 'Sitting', 7
    fighting = 'Fighting', 8
    standing = 'Standing', 9


class Rarity(CodedStrEnum):
    """Object rarity tier (rarity_types[])."""

    common = 'common', 0
    uncommon = 'uncommon', 1
    rare = 'rare', 2
    epic = 'epic', 3
    legendary = 'legendary', 4
    godly = 'godly', 5
    immortal = 'immortal', 6


class Material(CodedStrEnum):
    """What an object is made of (material_types[])."""

    none_ = 'none', 0
    adamantium = 'adamantium', 1
    aluminum = 'aluminum', 2
    bone = 'bone', 3
    brass = 'brass', 4
    bronze = 'bronze', 5
    carbon = 'carbon', 6
    ceramic = 'ceramic', 7
    cloth = 'cloth', 8
    copper = 'copper', 9
    crystal = 'crystal', 10
    fur = 'fur', 11
    gemstone = 'gemstone', 12
    glass = 'glass', 13
    gold = 'gold', 14
    ice = 'ice', 15
    iron = 'iron', 16
    lead = 'lead', 17
    leather = 'leather', 18
    mithril = 'mithril', 19
    organic = 'organic', 20
    paper = 'paper', 21
    plastic = 'plastic', 22
    platinum = 'platinum', 23
    scale = 'scale', 24
    silk = 'silk', 25
    silver = 'silver', 26
    steel = 'steel', 27
    stone = 'stone', 28
    tin = 'tin', 29
    titanium = 'titanium', 30
    wax = 'wax', 31
    wood = 'wood', 32
    zinc = 'zinc', 33
    banded = 'banded', 34


class WeaponClass(CodedStrEnum):
    """Weapon proficiency class (weapon_types[])."""

    none_ = 'none', 0
    dagger = 'dagger', 1
    knife = 'knife', 2
    shortsword = 'shortsword', 3
    longsword = 'longsword', 4
    broadsword = 'broadsword', 5
    bastard = 'bastard', 6
    claymore = 'claymore', 7
    scimitar = 'scimitar', 8
    rapier = 'rapier', 9
    sabre = 'sabre', 10
    club = 'club', 11
    staff = 'staff', 12
    mace = 'mace', 13
    whip = 'whip', 14
    handaxe = 'handaxe', 15
    battleaxe = 'battleaxe', 16
    halberd = 'halberd', 17
    pike = 'pike', 18
    glaive = 'glaive', 19
    longbow = 'longbow', 20
    shortbow = 'shortbow', 21
    crossbow = 'crossbow', 22
    spear = 'spear', 23
    javelin = 'javelin', 24
    trident = 'trident', 25
    flail = 'flail', 26
    dart = 'dart', 27
    shuriken = 'shuriken', 28
    claw = 'claw', 29
    scythe = 'scythe', 30
    pickaxe = 'pickaxe', 31
    axe = 'axe', 32
    warhammer = 'warhammer', 33
    hammer = 'hammer', 34


class DamageType(CodedStrEnum):
    """Weapon damage type (damage_types[])."""

    smite = 'smite', 0
    stab = 'stab', 1
    whip = 'whip', 2
    slash = 'slash', 3
    smash = 'smash', 4
    cleave = 'cleave', 5
    crush = 'crush', 6
    bludgeon = 'bludgeon', 7
    claw = 'claw', 8
    bite = 'bite', 9
    sting = 'sting', 10
    pierce = 'pierce', 11


class Drink(CodedStrEnum):
    """Liquid in a drink container (drinks[])."""

    water = 'water', 0
    beer = 'beer', 1
    wine = 'wine', 2
    ale = 'ale', 3
    dark_ale = 'dark ale', 4
    whisky = 'whisky', 5
    lemonade = 'lemonade', 6
    firebreather = 'firebreather', 7
    local_speciality = 'local speciality', 8
    slime_mold_juice = 'slime mold juice', 9
    milk = 'milk', 10
    tea = 'tea', 11
    coffee = 'coffee', 12
    blood = 'blood', 13
    salt_water = 'salt water', 14
    coke = 'coke', 15


class ItemKind(CodedStrEnum):
    """Object type name as the server prints it (item_types[])."""

    undefined = 'undefined', 0
    light = 'light', 1
    scroll = 'scroll', 2
    wand = 'wand', 3
    staff = 'staff', 4
    weapon = 'weapon', 5
    fire_weapon = 'fire weapon', 6
    missile = 'missile', 7
    treasure = 'treasure', 8
    armor = 'armor', 9
    potion = 'potion', 10
    worn = 'worn', 11
    other = 'other', 12
    trash = 'trash', 13
    trap = 'trap', 14
    container = 'container', 15
    note = 'note', 16
    liquid_container = 'liquid container', 17
    key = 'key', 18
    food = 'food', 19
    money = 'money', 20
    pen = 'pen', 21
    boat = 'boat', 22
    audio = 'audio', 23
    board = 'board', 24
    book = 'book', 25
    pouch = 'pouch', 26
    component = 'component', 27
    hierarchical = 'hierarchical', 28
    spell_gem = 'spell gem', 29
    set_item = 'set item', 30
    socket = 'socket', 31


class RaceName(CodedStrEnum):
    """Race by name; code is the race vnum (race_list[])."""

    none_ = 'None', 0
    human = 'Human', 1
    elven = 'Elven', 2
    dwarf = 'Dwarf', 3
    hobbit = 'Hobbit', 4
    gnome = 'Gnome', 5
    reptile = 'Reptile', 6
    special = 'Special', 7
    lycanthrope = 'Lycanthrope', 8
    dragon = 'Dragon', 9
    undead = 'Undead', 10
    orc = 'Orc', 11
    insect = 'Insect', 12
    arachnid = 'Arachnid', 13
    dinosaur = 'Dinosaur', 14
    fish = 'Fish', 15
    bird = 'Bird', 16
    giant = 'Giant', 17
    predator = 'Predator', 18
    parasite = 'Parasite', 19
    slime = 'Slime', 20
    demon = 'Demon', 21
    snake = 'Snake', 22
    herbiv = 'Herbiv', 23
    tree = 'Tree', 24
    veggie = 'Veggie', 25
    element = 'Element', 26
    planar = 'Planar', 27
    devil = 'Devil', 28
    ghost = 'Ghost', 29
    goblin = 'Goblin', 30
    troll = 'Troll', 31
    vegman = 'Vegman', 32
    mindflayer = 'MindFlayer', 33
    primate = 'Primate', 34
    enfan = 'Enfan', 35
    rat = 'Rat', 36
    turtle = 'Turtle', 37
    n38 = '38', 38
    n39 = '39', 39
    patryn = 'Patryn', 40
    labrat = 'Labrat', 41
    sartan = 'Sartan', 42
    tytan = 'Tytan', 43
    n44 = '44', 44
    mutant = 'Mutant', 45
    halfbreed = 'Halfbreed', 46
    half_elf = 'Half-Elf', 47
    halfling = 'Halfling', 48
    half_orc = 'Half-Orc', 49
    ogre = 'Ogre', 50
    pixie = 'Pixie', 51
    lizardman = 'Lizardman', 52
    snail = 'Snail', 53
    daevish = 'Daevish', 54
    vampire = 'Vampire', 55


class ClassName(CodedStrEnum):
    """Character/mob class name (class_list[])."""

    assassin = 'assassin', 0
    avenger = 'avenger', 1
    barbarian = 'barbarian', 2
    bard = 'bard', 3
    cavalier = 'cavalier', 4
    cleric = 'cleric', 5
    druid = 'druid', 6
    illusionist = 'illusionist', 7
    mage = 'mage', 8
    ninja = 'ninja', 9
    paladin = 'paladin', 10
    ranger = 'ranger', 11
    thief = 'thief', 12
    warrior = 'warrior', 13
    highwayman = 'highwayman', 14
    swashbuckler = 'swashbuckler', 15
    powermonger = 'powermonger', 16
    scout = 'scout', 17
    templar = 'templar', 18
    expositor = 'expositor', 19
    scholar = 'scholar', 20
    necromancer = 'necromancer', 21
    warlock = 'warlock', 22
    warlord = 'warlord', 23
    forester = 'forester', 24
    herbalist = 'herbalist', 25
    celtic = 'celtic', 26
    woodsman = 'woodsman', 27
    overlord = 'overlord', 28
    sohei = 'sohei', 29
    brigand = 'brigand', 30
    dragoon = 'dragoon', 31
    mercenary = 'mercenary', 32
    warder = 'warder', 33
    builder = 'builder', 34
    immortal = 'immortal', 35
    inquisitor = 'inquisitor', 36
    wizard = 'wizard', 37
    reaver = 'reaver', 38


class RoomFlag(CodedFlag):
    """Room flag (room_bits[])."""

    dark = 0, 'dark'
    death = 1, 'death'
    no_mob = 2, 'no_mob'
    indoors = 3, 'indoors'
    peaceful = 4, 'peaceful'
    nosteal = 5, 'nosteal'
    no_sum = 6, 'no_sum'
    no_magic = 7, 'no_magic'
    tunnel = 8, 'tunnel'
    private = 9, 'private'
    no_goto = 10, 'no_goto'
    anti_good = 11, 'anti_good'
    anti_neutral = 12, 'anti_neutral'
    anti_evil = 13, 'anti_evil'
    lord_only = 14, 'lord_only'
    rent_room = 15, 'rent_room'
    arena = 16, 'arena'
    fast_mana = 17, 'fast_mana'
    fast_hit_points = 18, 'fast_hit_points'
    fast_moves = 19, 'fast_moves'
    mapable = 20, 'mapable'
    noshowexit = 21, 'noshowexit'
    fall = 22, 'fall'
    good_altar = 23, 'good_altar'
    neutral_altar = 24, 'neutral_altar'
    evil_altar = 25, 'evil_altar'
    relocate_distort = 26, 'relocate_distort'
    summon_trap = 27, 'summon_trap'
    blue_glow = 28, 'blue_glow'
    dispel_magic = 29, 'dispel_magic'
    autosave = 30, 'autosave'
    point_of_interest = 31, 'point_of_interest'


class ExitFlag(CodedFlag):
    """Door/exit flag (exit_bits[])."""

    door = 0, 'door'
    closed = 1, 'closed'
    locked = 2, 'locked'
    secret = 3, 'secret'
    pickproof = 4, 'pickproof'
    knockable = 5, 'knockable'
    hidden = 6, 'hidden'
    message = 7, 'message'
    autoclose = 8, 'autoclose'
    autolock = 9, 'autolock'
    crackable = 10, 'crackable'


class ContainerFlag(CodedFlag):
    """Container state flag (container_bits[])."""

    closeable = 0, 'closeable'
    pickproof = 1, 'pickproof'
    closed = 2, 'closed'
    locked = 3, 'locked'
    knockable = 4, 'knockable'
    crackable = 5, 'crackable'


class BoardFlag(CodedFlag):
    """Bulletin board permission flag (board_bits[])."""

    mortal_read = 0, 'mortal_read'
    mortal_write = 1, 'mortal_write'
    mortal_remove = 2, 'mortal_remove'
    immortal_read = 3, 'immortal_read'
    immortal_write = 4, 'immortal_write'
    immortal_remove = 5, 'immortal_remove'
    imp_read = 6, 'imp_read'
    imp_write = 7, 'imp_write'
    imp_remove = 8, 'imp_remove'
    police_read = 9, 'police_read'
    police_write = 10, 'police_write'
    police_remove = 11, 'police_remove'


class WearFlag(CodedFlag):
    """Where an object can be worn (wear_bits[])."""

    take = 0, 'take'
    finger = 1, 'finger'
    neck = 2, 'neck'
    body = 3, 'body'
    head = 4, 'head'
    legs = 5, 'legs'
    feet = 6, 'feet'
    hands = 7, 'hands'
    arms = 8, 'arms'
    shield = 9, 'shield'
    about = 10, 'about'
    waist = 11, 'waist'
    wrist = 12, 'wrist'
    wield = 13, 'wield'
    hold = 14, 'hold'
    throw = 15, 'throw'
    light = 16, 'light'
    damaged = 17, 'damaged'
    construction = 18, 'construction'
    pouch = 19, 'pouch'
    dual_wield = 20, 'dual-wield'
    dual_wield_only = 21, 'dual-wield-only'
    wings = 22, 'wings'
    trinket = 23, 'trinket'


class ObjectFlag(CodedFlag):
    """Object extra flag: glow, hum, magic, cursed ... (extra_bits[])."""

    glow = 0, 'glow'
    hum = 1, 'hum'
    flexible = 2, 'flexible'
    mundane = 3, 'mundane'
    nodrop = 4, 'NODROP'
    invisible = 5, 'invisible'
    magic = 6, 'magic'
    cursed = 7, 'cursed'
    bless = 8, 'bless'
    anti_good = 9, 'anti-good'
    anti_evil = 10, 'anti-evil'
    anti_neutral = 11, 'anti-neutral'
    random = 12, 'random'
    hidden = 13, 'hidden'
    tbd14 = 14, 'tbd14'
    tbd15 = 15, 'tbd15'
    tbd16 = 16, 'tbd16'
    tbd17 = 17, 'tbd17'
    tbd18 = 18, 'tbd18'
    tbd19 = 19, 'tbd19'
    tbd20 = 20, 'tbd20'
    tbd21 = 21, 'tbd21'
    tbd22 = 22, 'tbd22'
    tbd23 = 23, 'tbd23'
    tbd24 = 24, 'tbd24'
    tbd25 = 25, 'tbd25'
    tbd26 = 26, 'tbd26'
    tbd27 = 27, 'tbd27'
    tbd28 = 28, 'tbd28'
    no_damage = 29, 'no-damage'
    arena_only = 30, 'arena-only'
    test_item = 31, 'test-item'


class MobAction(CodedFlag):
    """Mob behaviour flag (action_bits[])."""

    special = 0, 'special'
    sentinel = 1, 'sentinel'
    scavenger = 2, 'scavenger'
    npc = 3, 'npc'
    nice_thief = 4, 'nice-thief'
    aggressive = 5, 'aggressive'
    stay_zone = 6, 'stay-zone'
    wimpy = 7, 'wimpy'
    annoying = 8, 'annoying'
    hateful = 9, 'hateful'
    afraid = 10, 'afraid'
    immortal = 11, 'immortal'
    hunting = 12, 'hunting'
    deadly = 13, 'deadly'
    polymorphed_self = 14, 'polymorphed'
    polymorphed_other = 15, 'polymorphed'
    guarding = 16, 'guarding'
    citizen = 17, 'citizen'
    healer = 18, 'healer'
    nosummon = 19, 'nosummon'
    far_track = 20, 'far-track'
    travelling = 21, 'travelling'
    no_wear = 22, 'no-wear'


class AffectBit(CodedFlag):
    """Spell affect bit on a character or granted by an object (affected_bits[])."""

    undefined = 0, 'undefined*'
    blind = 1, 'blind'
    invisible = 2, 'invisible'
    detect_evil = 3, 'detect-evil'
    detect_invisible = 4, 'detect-invisible'
    detect_magic = 5, 'detect-magic'
    sense_life = 6, 'sense-life'
    hold = 7, 'hold'
    sanctuary = 8, 'sanctuary'
    group = 9, 'group'
    curse = 10, 'curse'
    flying = 11, 'flying'
    poison = 12, 'poison'
    protect_evil = 13, 'protect-evil'
    paralysis = 14, 'paralysis'
    infravision = 15, 'infravision'
    water_breath = 16, 'water-breath'
    sleep = 17, 'sleep'
    sneak = 18, 'sneak'
    hide = 19, 'hide'
    fear = 20, 'fear'
    charm = 21, 'charm'
    follow = 22, 'follow'
    true_sight = 23, 'true-sight'
    scrying = 24, 'scrying'
    fireshield = 25, 'fireshield'
    invulnerability = 26, 'invulnerability'
    berserk = 27, 'berserk'
    berserk_recover = 28, 'berserk-recover'
    nosleep = 29, 'nosleep'
    nosummon = 30, 'nosummon'
    nocharm = 31, 'nocharm'
    recharger = 32, 'recharger'
    vitality = 33, 'vitality'
    farsee = 34, 'farsee'
    nofear = 35, 'nofear'
    calm = 36, 'calm'
    bit37 = 37, 'bit37'    # no name in the C table
    bit38 = 38, 'bit38'    # no name in the C table
    bit39 = 39, 'bit39'    # no name in the C table
    no_poison = 40, 'no-poison'
    bearform = 41, 'bearform'
    catform = 42, 'catform'
    boomform = 43, 'boomform'
    treeform = 44, 'treeform'
    normform = 45, 'normform'
    bit46 = 46, 'bit46'    # no name in the C table


class Immunity(CodedFlag):
    """Damage class for immune/resistant/susceptible (immunity_names[])."""

    fire = 0, 'fire'
    cold = 1, 'cold'
    electricity = 2, 'electricity'
    energy = 3, 'energy'
    blunt = 4, 'blunt'
    pierce = 5, 'pierce'
    slash = 6, 'slash'
    acid = 7, 'acid'
    poison = 8, 'poison'
    drain = 9, 'drain'
    sleep = 10, 'sleep'
    charm = 11, 'charm'
    hold = 12, 'hold'
    non_magical = 13, 'non-magical'
    plus_1 = 14, 'plus 1'
    plus_2 = 15, 'plus 2'
    plus_3 = 16, 'plus 3'
    plus_4 = 17, 'plus 4'
    backstab = 18, 'backstab'
    n20 = 19, '20'
    n21 = 20, '21'
    n22 = 21, '22'
    n23 = 22, '23'
    n24 = 23, '24'
    n25 = 24, '25'
    n26 = 25, '26'
    n27 = 26, '27'
    n28 = 27, '28'
    n29 = 28, '29'
    n30 = 29, '30'
    n31 = 30, '31'
    n32 = 31, '32'


class SectorFlag(CodedFlag):
    """Sector flag (sector_bits[])."""

    no_weather = 0, 'no_weather'
    fly_only = 1, 'fly_only'
    water_breath = 2, 'water_breath'
    no_spells = 3, 'no_spells'
    prototype = 4, 'prototype'


class ClanFlag(CodedFlag):
    """Clan flag (clan_flags[])."""

    pkothers = 0, 'pkothers'
    pkclan = 1, 'pkclan'
    private = 2, 'private'
    stealth = 3, 'stealth'
    openenroll = 4, 'openenroll'
    bit5 = 5, 'bit5'    # no name in the C table


class TrapEffect(CodedFlag):
    """Trap effect flag (trap_eff_flags[])."""

    move = 0, 'move'
    object = 1, 'object'
    room = 2, 'room'
    north = 3, 'north'
    east = 4, 'east'
    south = 5, 'south'
    west = 6, 'west'
    up = 7, 'up'
    down = 8, 'down'
    northeast = 9, 'northeast'
    northwest = 10, 'northwest'
    southeast = 11, 'southeast'
    southwest = 12, 'southwest'


class PlayerFlag(CodedFlag):
    """Player act flag (player_bits[])."""

    brief = 0, 'BRIEF'
    noshout = 1, 'NOSHOUT'
    compact = 2, 'COMPACT'
    dontset = 3, 'DONTSET'
    wimpy = 4, 'WIMPY'
    nohassle = 5, 'NOHASSLE'
    stealth = 6, 'STEALTH'
    hunting = 7, 'HUNTING'
    deaf = 8, 'DEAF'
    echo = 9, 'ECHO'
    log = 10, 'LOG'
    noviewlog = 11, 'NOVIEWLOG'
    banished = 12, 'BANISHED'
    criminal = 13, 'CRIMINAL'
    notell = 14, 'NOTELL'
    auction = 15, 'AUCTION'
    nosports = 16, 'NOSPORTS'
    gossip = 17, 'GOSSIP'
    silenced = 18, 'SILENCED'
    veg = 19, 'VEG'
    debug = 20, 'DEBUG'
    noexits = 21, 'NOEXITS'
    questing = 22, 'QUESTING'
    police = 23, 'POLICE'
    tester = 24, 'TESTER'
    stupid = 25, 'STUPID'
    regen = 26, 'REGEN'
    priority = 27, 'PRIORITY'
    badname = 28, 'BADNAME'
    leash = 29, 'LEASH'
    anonymous = 30, 'ANONYMOUS'


class AccountFlag(CodedFlag):
    """Account flag (account_bits[])."""

    valid = 0, 'VALID'
    nonew = 1, 'NONEW'
    silenced = 2, 'SILENCED'
    stupid = 3, 'STUPID'
    banished = 4, 'BANISHED'
    log = 5, 'LOG'
    nopurge = 6, 'NOPURGE'
    noshout = 7, 'NOSHOUT'
    ver_exempt = 8, 'VER_EXEMPT'
    ver_mailed = 9, 'VER_MAILED'
    verified = 10, 'VERIFIED'


class Form(CodedFlag):
    """Body form of a race (forms[])."""

    humanoid = 0, 'humanoid'
    animal = 1, 'animal'
    undead = 2, 'undead'
    lycanthrope = 3, 'lycanthrope'
    diabolic = 4, 'diabolic'
    reptile = 5, 'reptile'
    nohands = 6, 'nohands'
    person = 7, 'person'
    extra_planar = 8, 'extra-planar'


class Intrinsic(CodedFlag):
    """Racial intrinsic ability (intrinsics[])."""

    infravision = 0, 'infravision'
    regeneration = 1, 'regeneration'
    fast_heal = 2, 'fast-heal'


class ApplyLocation(CodedStrEnum):
    """What an apply modifies (apply_types[])."""

    none_ = 'NONE', 0
    str = 'STR', 1
    dex = 'DEX', 2
    int = 'INT', 3
    wis = 'WIS', 4
    con = 'CON', 5
    cha = 'CHA', 6
    lck = 'LCK', 7
    level = 'LEVEL', 8
    age = 'AGE', 9
    char_weight = 'CHAR_WEIGHT', 10
    char_height = 'CHAR_HEIGHT', 11
    mana = 'MANA', 12
    hit = 'HIT', 13
    move = 'MOVE', 14
    gold = 'GOLD', 15
    exp = 'EXP', 16
    all_ac = 'ALL_AC', 17
    hitroll = 'HITROLL', 18
    damroll = 'DAMROLL', 19
    saving_para = 'SAVING_PARA', 20
    saving_rod = 'SAVING_ROD', 21
    saving_petri = 'SAVING_PETRI', 22
    saving_breath = 'SAVING_BREATH', 23
    saving_spell = 'SAVING_SPELL', 24
    saving_all = 'SAVING_ALL', 25
    resistance = 'RESISTANCE', 26
    susceptibility = 'SUSCEPTIBILITY', 27
    immunity = 'IMMUNITY', 28
    spell_affect = 'SPELL AFFECT', 29
    weapon_spell = 'WEAPON SPELL', 30
    eat_spell = 'EAT SPELL', 31
    backstab = 'BACKSTAB', 32
    kick = 'KICK', 33
    sneak = 'SNEAK', 34
    hide = 'HIDE', 35
    bash = 'BASH', 36
    pick = 'PICK', 37
    steal = 'STEAL', 38
    track = 'TRACK', 39
    hit_n_dam = 'HIT-N-DAM', 40
    feet_ac = 'FEET-AC', 41
    legs_ac = 'LEGS-AC', 42
    arms_ac = 'ARMS-AC', 43
    body_ac = 'BODY-AC', 44
    head_ac = 'HEAD-AC', 45
    all_stopping = 'ALL-STOPPING', 46
    feet_stopping = 'FEET-STOPPING', 47
    legs_stopping = 'LEGS-STOPPING', 48
    arms_stopping = 'ARMS-STOPPING', 49
    body_stopping = 'BODY-STOPPING', 50
    head_stopping = 'HEAD-STOPPING', 51
    batter = 'BATTER', 52
    power = 'POWER', 53
    fire_resist = 'FIRE RESIST', 54
    cold_resist = 'COLD RESIST', 55
    electric_resist = 'ELECTRIC RESIST', 56
    energy_resist = 'ENERGY RESIST', 57
    acid_resist = 'ACID RESIST', 58
    poison_resist = 'POISON RESIST', 59
    force_resist = 'FORCE RESIST', 60
    magic_resist = 'MAGIC RESIST', 61
    all_resists = 'ALL RESISTS', 62
    item_spell = 'ITEM SPELL', 63
    assassinate = 'ASSASSINATE', 64
    melee_haste = 'MELEE_HASTE', 65
    spell_haste = 'SPELL_HASTE', 66
    slow = 'SLOW', 67
    armor_penetration = 'ARMOR PENETRATION', 68
    fire_penetration = 'FIRE PENETRATION', 69
    cold_penetration = 'COLD PENETRATION', 70
    electricity_penetration = 'ELECTRICITY PENETRATION', 71
    water_penetration = 'WATER PENETRATION', 72
    acid_penetration = 'ACID PENETRATION', 73
    poison_penetration = 'POISON PENETRATION', 74
    force_penetration = 'FORCE PENETRATION', 75
    magic_penetration = 'MAGIC PENETRATION', 76
    light_penetration = 'LIGHT PENETRATION', 77
    dark_penetration = 'DARK PENETRATION', 78
    spell_power = 'SPELL POWER', 79
    water_resist = 'WATER RESIST', 80
    light_resist = 'LIGHT RESIST', 81
    life_steal = 'LIFE STEAL', 82
    penetrate_all = 'PENETRATE ALL', 83
    spell_vamp = 'SPELL VAMP', 84
    mana_regen = 'MANA REGEN', 85
    power_regen = 'POWER REGEN', 86
    hp_regen = 'HP REGEN', 87
    moves_regen = 'MOVES REGEN', 88
    all_attributes = 'ALL ATTRIBUTES', 89
    slicendice = 'SLICENDICE', 90
    daze = 'DAZE', 91
    cheapshot = 'CHEAPSHOT', 92
    preparation = 'PREPARATION', 93
    garrote = 'GARROTE', 94
    ambush = 'AMBUSH', 95
    vanish = 'VANISH', 96
    shadowform = 'SHADOWFORM', 97
    strike = 'STRIKE', 98
    crippling_strike = 'CRIPPLING STRIKE', 99
    holy_strike = 'HOLY STRIKE', 100
    mute_strike = 'MUTE STRIKE', 101
    peek = 'PEEK', 102
    whirlwind = 'WHIRLWIND', 103


class PulseType(CodedStrEnum):
    """What a pulse affect does on each pulse (PULSE_TYPE_*)."""

    none_ = 'none', 0
    buff = 'buff', 1
    heal = 'heal', 2
    damage = 'damage', 3
    shield = 'shield', 4


class WearPosition(CodedStrEnum):
    """Equipment slot (WEAR_* / WIELD / HOLD / POUCH), code 0..21."""

    light = 'light', 0
    finger_r = 'finger_r', 1
    finger_l = 'finger_l', 2
    neck_1 = 'neck_1', 3
    neck_2 = 'neck_2', 4
    body = 'body', 5
    head = 'head', 6
    legs = 'legs', 7
    feet = 'feet', 8
    hands = 'hands', 9
    arms = 'arms', 10
    shield = 'shield', 11
    about = 'about', 12
    waist = 'waist', 13
    wrist_r = 'wrist_r', 14
    wrist_l = 'wrist_l', 15
    wield = 'wield', 16
    hold = 'hold', 17
    pouch = 'pouch', 18
    wings = 'wings', 19
    trinket_r = 'trinket_r', 20
    trinket_l = 'trinket_l', 21


class ConfigFlag(CodedFlag):
    """Player display/behaviour preference (CONFIG_*)."""

    map_ = 0, 'map'
    manual_unlock = 1, 'manual_unlock'
    auto_split = 2, 'auto_split'
    short_descs = 3, 'short_descs'
    timestamps = 4, 'timestamps'
    keywords = 5, 'keywords'
    hunger = 6, 'hunger'
    channames = 7, 'channames'


class LogFlag(CodedFlag):
    """Server log channel (LOG_*)."""

    connection = 0, 'connection'
    mortspy = 1, 'mortspy'
    immspy = 2, 'immspy'
    urgent = 3, 'urgent'
    debug = 4, 'debug'
    reject = 5, 'reject'
    misc = 6, 'misc'
    death = 7, 'death'
    bugs = 8, 'bugs'
    ideas = 9, 'ideas'
    typos = 10, 'typos'
    thief = 11, 'thief'
    fine = 12, 'fine'
    link = 13, 'link'
    fall = 14, 'fall'
    banished = 15, 'banished'
    cheat = 16, 'cheat'
    imp = 17, 'imp'
    account = 18, 'account'
    load_obj = 19, 'load_obj'
    malloc = 20, 'malloc'
    aloginout = 21, 'aloginout'
    delete = 22, 'delete'
    zone = 23, 'zone'
    quest = 24, 'quest'
    police = 25, 'police'
    consent = 26, 'consent'
    board = 27, 'board'
    teleport = 28, 'teleport'
    help = 29, 'help'
    pulseaff = 30, 'pulseaff'
    mobcast = 31, 'mobcast'


class ClanRank(CodedStrEnum):
    """Rank within a clan (clan_ranks[])."""

    member = 'Member', 0
    officer = 'Officer', 1
    leader = 'Leader', 2
    owner = 'Owner', 3
