"""Fixed vocabularies of the game as StrEnums. GENERATED by tools/gen_enums.py
from the C name tables; do not edit by hand.

Each member's value is the string the game uses (and the JSONL carries); its
``code`` is the numeric code or bit index in the C table. Convert with
``member.code`` and ``Enum.from_code(n)``; for flag sets ``Enum.from_bits(word)``
/ ``Enum.to_bits(members)`` handle a 32-bit word and ``from_words`` /
``to_words`` a u32[8] extended bitvector.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Iterable


class CodedStrEnum(StrEnum):
    """A StrEnum whose members also carry the game's numeric code."""

    code: int

    def __new__(cls, value: str, code: int):
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.code = code
        return obj

    @classmethod
    def from_code(cls, code: int):
        """Member for a numeric code (codes of duplicated names resolve too)."""
        for m in cls:
            if m.code == code:
                return m
        name = _ALIAS_CODES.get(cls, {}).get(code)
        if name is not None:
            return cls(name)
        raise ValueError(f"{cls.__name__}: no member with code {code}")

    @classmethod
    def from_bits(cls, word: int) -> list:
        """Members whose bit is set in a 32-bit flag word."""
        return [m for m in cls if m.code < 32 and word & (1 << m.code)]

    @classmethod
    def from_words(cls, words: Iterable[int]) -> list:
        """Members set in a u32[n] extended bitvector."""
        words = list(words)
        return [m for m in cls
                if m.code // 32 < len(words) and words[m.code // 32] & (1 << (m.code % 32))]

    @classmethod
    def to_bits(cls, members: Iterable) -> int:
        """32-bit flag word from members (codes above 31 need to_words)."""
        word = 0
        for m in members:
            word |= 1 << cls(m).code
        return word

    @classmethod
    def to_words(cls, members: Iterable, n: int = 8) -> list[int]:
        """u32[n] extended bitvector from members."""
        words = [0] * n
        for m in members:
            c = cls(m).code
            words[c // 32] |= 1 << (c % 32)
        return words


# codes whose name duplicates an earlier member's (a few C tables repeat names)
_ALIAS_CODES: dict[type, dict[int, str]] = {}



class Direction(CodedStrEnum):
    """Exit direction; code is the exit array index (dirs[])."""

    north = 'north', 0
    east = 'east', 1
    south = 'south', 2
    west = 'west', 3
    up = 'up', 4
    down = 'down', 5
    northeast = 'northeast', 6
    southeast = 'southeast', 7
    southwest = 'southwest', 8
    northwest = 'northwest', 9


class Sex(CodedStrEnum):
    """Character sex (sexes[])."""

    neuter = 'neuter', 0
    male = 'male', 1
    female = 'female', 2


class Position(CodedStrEnum):
    """Character position, from dead to standing (position_types[])."""

    dead = 'Dead', 0
    mortally_wounded = 'Mortally wounded', 1
    incapacitated = 'Incapacitated', 2
    stunned = 'Stunned', 3
    sleeping = 'Sleeping', 4
    resting = 'Resting', 5
    praying = 'Praying', 6
    sitting = 'Sitting', 7
    fighting = 'Fighting', 8
    standing = 'Standing', 9


class Rarity(CodedStrEnum):
    """Object rarity tier (rarity_types[])."""

    common = 'common', 0
    uncommon = 'uncommon', 1
    rare = 'rare', 2
    epic = 'epic', 3
    legendary = 'legendary', 4
    godly = 'godly', 5
    immortal = 'immortal', 6


class Material(CodedStrEnum):
    """What an object is made of (material_types[])."""

    none_ = 'none', 0
    adamantium = 'adamantium', 1
    aluminum = 'aluminum', 2
    bone = 'bone', 3
    brass = 'brass', 4
    bronze = 'bronze', 5
    carbon = 'carbon', 6
    ceramic = 'ceramic', 7
    cloth = 'cloth', 8
    copper = 'copper', 9
    crystal = 'crystal', 10
    fur = 'fur', 11
    gemstone = 'gemstone', 12
    glass = 'glass', 13
    gold = 'gold', 14
    ice = 'ice', 15
    iron = 'iron', 16
    lead = 'lead', 17
    leather = 'leather', 18
    mithril = 'mithril', 19
    organic = 'organic', 20
    paper = 'paper', 21
    plastic = 'plastic', 22
    platinum = 'platinum', 23
    scale = 'scale', 24
    silk = 'silk', 25
    silver = 'silver', 26
    steel = 'steel', 27
    stone = 'stone', 28
    tin = 'tin', 29
    titanium = 'titanium', 30
    wax = 'wax', 31
    wood = 'wood', 32
    zinc = 'zinc', 33
    banded = 'banded', 34


class WeaponClass(CodedStrEnum):
    """Weapon proficiency class (weapon_types[])."""

    none_ = 'none', 0
    dagger = 'dagger', 1
    knife = 'knife', 2
    shortsword = 'shortsword', 3
    longsword = 'longsword', 4
    broadsword = 'broadsword', 5
    bastard = 'bastard', 6
    claymore = 'claymore', 7
    scimitar = 'scimitar', 8
    rapier = 'rapier', 9
    sabre = 'sabre', 10
    club = 'club', 11
    staff = 'staff', 12
    mace = 'mace', 13
    whip = 'whip', 14
    handaxe = 'handaxe', 15
    battleaxe = 'battleaxe', 16
    halberd = 'halberd', 17
    pike = 'pike', 18
    glaive = 'glaive', 19
    longbow = 'longbow', 20
    shortbow = 'shortbow', 21
    crossbow = 'crossbow', 22
    spear = 'spear', 23
    javelin = 'javelin', 24
    trident = 'trident', 25
    flail = 'flail', 26
    dart = 'dart', 27
    shuriken = 'shuriken', 28
    claw = 'claw', 29
    scythe = 'scythe', 30
    pickaxe = 'pickaxe', 31
    axe = 'axe', 32
    warhammer = 'warhammer', 33
    hammer = 'hammer', 34


class DamageType(CodedStrEnum):
    """Weapon damage type (damage_types[])."""

    smite = 'smite', 0
    stab = 'stab', 1
    whip = 'whip', 2
    slash = 'slash', 3
    smash = 'smash', 4
    cleave = 'cleave', 5
    crush = 'crush', 6
    bludgeon = 'bludgeon', 7
    claw = 'claw', 8
    bite = 'bite', 9
    sting = 'sting', 10
    pierce = 'pierce', 11


class Drink(CodedStrEnum):
    """Liquid in a drink container (drinks[])."""

    water = 'water', 0
    beer = 'beer', 1
    wine = 'wine', 2
    ale = 'ale', 3
    dark_ale = 'dark ale', 4
    whisky = 'whisky', 5
    lemonade = 'lemonade', 6
    firebreather = 'firebreather', 7
    local_speciality = 'local speciality', 8
    slime_mold_juice = 'slime mold juice', 9
    milk = 'milk', 10
    tea = 'tea', 11
    coffee = 'coffee', 12
    blood = 'blood', 13
    salt_water = 'salt water', 14
    coke = 'coke', 15


class ItemKind(CodedStrEnum):
    """Object type name as the server prints it (item_types[])."""

    undefined = 'undefined', 0
    light = 'light', 1
    scroll = 'scroll', 2
    wand = 'wand', 3
    staff = 'staff', 4
    weapon = 'weapon', 5
    fire_weapon = 'fire weapon', 6
    missile = 'missile', 7
    treasure = 'treasure', 8
    armor = 'armor', 9
    potion = 'potion', 10
    worn = 'worn', 11
    other = 'other', 12
    trash = 'trash', 13
    trap = 'trap', 14
    container = 'container', 15
    note = 'note', 16
    liquid_container = 'liquid container', 17
    key = 'key', 18
    food = 'food', 19
    money = 'money', 20
    pen = 'pen', 21
    boat = 'boat', 22
    audio = 'audio', 23
    board = 'board', 24
    book = 'book', 25
    pouch = 'pouch', 26
    component = 'component', 27
    hierarchical = 'hierarchical', 28
    spell_gem = 'spell gem', 29
    set_item = 'set item', 30
    socket = 'socket', 31


class RaceName(CodedStrEnum):
    """Race by name; code is the race vnum (race_list[])."""

    none_ = 'None', 0
    human = 'Human', 1
    elven = 'Elven', 2
    dwarf = 'Dwarf', 3
    hobbit = 'Hobbit', 4
    gnome = 'Gnome', 5
    reptile = 'Reptile', 6
    special = 'Special', 7
    lycanthrope = 'Lycanthrope', 8
    dragon = 'Dragon', 9
    undead = 'Undead', 10
    orc = 'Orc', 11
    insect = 'Insect', 12
    arachnid = 'Arachnid', 13
    dinosaur = 'Dinosaur', 14
    fish = 'Fish', 15
    bird = 'Bird', 16
    giant = 'Giant', 17
    predator = 'Predator', 18
    parasite = 'Parasite', 19
    slime = 'Slime', 20
    demon = 'Demon', 21
    snake = 'Snake', 22
    herbiv = 'Herbiv', 23
    tree = 'Tree', 24
    veggie = 'Veggie', 25
    element = 'Element', 26
    planar = 'Planar', 27
    devil = 'Devil', 28
    ghost = 'Ghost', 29
    goblin = 'Goblin', 30
    troll = 'Troll', 31
    vegman = 'Vegman', 32
    mindflayer = 'MindFlayer', 33
    primate = 'Primate', 34
    enfan = 'Enfan', 35
    rat = 'Rat', 36
    turtle = 'Turtle', 37
    n38 = '38', 38
    n39 = '39', 39
    patryn = 'Patryn', 40
    labrat = 'Labrat', 41
    sartan = 'Sartan', 42
    tytan = 'Tytan', 43
    n44 = '44', 44
    mutant = 'Mutant', 45
    halfbreed = 'Halfbreed', 46
    half_elf = 'Half-Elf', 47
    halfling = 'Halfling', 48
    half_orc = 'Half-Orc', 49
    ogre = 'Ogre', 50
    pixie = 'Pixie', 51
    lizardman = 'Lizardman', 52
    snail = 'Snail', 53
    daevish = 'Daevish', 54
    vampire = 'Vampire', 55


class ClassName(CodedStrEnum):
    """Character/mob class name (class_list[])."""

    assassin = 'assassin', 0
    avenger = 'avenger', 1
    barbarian = 'barbarian', 2
    bard = 'bard', 3
    cavalier = 'cavalier', 4
    cleric = 'cleric', 5
    druid = 'druid', 6
    illusionist = 'illusionist', 7
    mage = 'mage', 8
    ninja = 'ninja', 9
    paladin = 'paladin', 10
    ranger = 'ranger', 11
    thief = 'thief', 12
    warrior = 'warrior', 13
    highwayman = 'highwayman', 14
    swashbuckler = 'swashbuckler', 15
    powermonger = 'powermonger', 16
    scout = 'scout', 17
    templar = 'templar', 18
    expositor = 'expositor', 19
    scholar = 'scholar', 20
    necromancer = 'necromancer', 21
    warlock = 'warlock', 22
    warlord = 'warlord', 23
    forester = 'forester', 24
    herbalist = 'herbalist', 25
    celtic = 'celtic', 26
    woodsman = 'woodsman', 27
    overlord = 'overlord', 28
    sohei = 'sohei', 29
    brigand = 'brigand', 30
    dragoon = 'dragoon', 31
    mercenary = 'mercenary', 32
    warder = 'warder', 33
    builder = 'builder', 34
    immortal = 'immortal', 35
    inquisitor = 'inquisitor', 36
    wizard = 'wizard', 37
    reaver = 'reaver', 38


class RoomFlag(CodedStrEnum):
    """Room flag (room_bits[])."""

    dark = 'dark', 0
    death = 'death', 1
    no_mob = 'no_mob', 2
    indoors = 'indoors', 3
    peaceful = 'peaceful', 4
    nosteal = 'nosteal', 5
    no_sum = 'no_sum', 6
    no_magic = 'no_magic', 7
    tunnel = 'tunnel', 8
    private = 'private', 9
    no_goto = 'no_goto', 10
    anti_good = 'anti_good', 11
    anti_neutral = 'anti_neutral', 12
    anti_evil = 'anti_evil', 13
    lord_only = 'lord_only', 14
    rent_room = 'rent_room', 15
    arena = 'arena', 16
    fast_mana = 'fast_mana', 17
    fast_hit_points = 'fast_hit_points', 18
    fast_moves = 'fast_moves', 19
    mapable = 'mapable', 20
    noshowexit = 'noshowexit', 21
    fall = 'fall', 22
    good_altar = 'good_altar', 23
    neutral_altar = 'neutral_altar', 24
    evil_altar = 'evil_altar', 25
    relocate_distort = 'relocate_distort', 26
    summon_trap = 'summon_trap', 27
    blue_glow = 'blue_glow', 28
    dispel_magic = 'dispel_magic', 29
    autosave = 'autosave', 30
    point_of_interest = 'point_of_interest', 31


class ExitFlag(CodedStrEnum):
    """Door/exit flag (exit_bits[])."""

    door = 'door', 0
    closed = 'closed', 1
    locked = 'locked', 2
    secret = 'secret', 3
    pickproof = 'pickproof', 4
    knockable = 'knockable', 5
    hidden = 'hidden', 6
    message = 'message', 7
    autoclose = 'autoclose', 8
    autolock = 'autolock', 9
    crackable = 'crackable', 10


class ContainerFlag(CodedStrEnum):
    """Container state flag (container_bits[])."""

    closeable = 'closeable', 0
    pickproof = 'pickproof', 1
    closed = 'closed', 2
    locked = 'locked', 3
    knockable = 'knockable', 4
    crackable = 'crackable', 5


class BoardFlag(CodedStrEnum):
    """Bulletin board permission flag (board_bits[])."""

    mortal_read = 'mortal_read', 0
    mortal_write = 'mortal_write', 1
    mortal_remove = 'mortal_remove', 2
    immortal_read = 'immortal_read', 3
    immortal_write = 'immortal_write', 4
    immortal_remove = 'immortal_remove', 5
    imp_read = 'imp_read', 6
    imp_write = 'imp_write', 7
    imp_remove = 'imp_remove', 8
    police_read = 'police_read', 9
    police_write = 'police_write', 10
    police_remove = 'police_remove', 11


class WearFlag(CodedStrEnum):
    """Where an object can be worn (wear_bits[])."""

    take = 'take', 0
    finger = 'finger', 1
    neck = 'neck', 2
    body = 'body', 3
    head = 'head', 4
    legs = 'legs', 5
    feet = 'feet', 6
    hands = 'hands', 7
    arms = 'arms', 8
    shield = 'shield', 9
    about = 'about', 10
    waist = 'waist', 11
    wrist = 'wrist', 12
    wield = 'wield', 13
    hold = 'hold', 14
    throw = 'throw', 15
    light = 'light', 16
    damaged = 'damaged', 17
    construction = 'construction', 18
    pouch = 'pouch', 19
    dual_wield = 'dual-wield', 20
    dual_wield_only = 'dual-wield-only', 21
    wings = 'wings', 22
    trinket = 'trinket', 23


class ObjectFlag(CodedStrEnum):
    """Object extra flag: glow, hum, magic, cursed ... (extra_bits[])."""

    glow = 'glow', 0
    hum = 'hum', 1
    flexible = 'flexible', 2
    mundane = 'mundane', 3
    nodrop = 'NODROP', 4
    invisible = 'invisible', 5
    magic = 'magic', 6
    cursed = 'cursed', 7
    bless = 'bless', 8
    anti_good = 'anti-good', 9
    anti_evil = 'anti-evil', 10
    anti_neutral = 'anti-neutral', 11
    random = 'random', 12
    hidden = 'hidden', 13
    tbd14 = 'tbd14', 14
    tbd15 = 'tbd15', 15
    tbd16 = 'tbd16', 16
    tbd17 = 'tbd17', 17
    tbd18 = 'tbd18', 18
    tbd19 = 'tbd19', 19
    tbd20 = 'tbd20', 20
    tbd21 = 'tbd21', 21
    tbd22 = 'tbd22', 22
    tbd23 = 'tbd23', 23
    tbd24 = 'tbd24', 24
    tbd25 = 'tbd25', 25
    tbd26 = 'tbd26', 26
    tbd27 = 'tbd27', 27
    tbd28 = 'tbd28', 28
    no_damage = 'no-damage', 29
    arena_only = 'arena-only', 30
    test_item = 'test-item', 31


class MobAction(CodedStrEnum):
    """Mob behaviour flag (action_bits[])."""

    special = 'special', 0
    sentinel = 'sentinel', 1
    scavenger = 'scavenger', 2
    npc = 'npc', 3
    nice_thief = 'nice-thief', 4
    aggressive = 'aggressive', 5
    stay_zone = 'stay-zone', 6
    wimpy = 'wimpy', 7
    annoying = 'annoying', 8
    hateful = 'hateful', 9
    afraid = 'afraid', 10
    immortal = 'immortal', 11
    hunting = 'hunting', 12
    deadly = 'deadly', 13
    polymorphed = 'polymorphed', 14
    # code 15 is also 'polymorphed' (see polymorphed)
    guarding = 'guarding', 16
    citizen = 'citizen', 17
    healer = 'healer', 18
    nosummon = 'nosummon', 19
    far_track = 'far-track', 20
    travelling = 'travelling', 21
    no_wear = 'no-wear', 22


class AffectBit(CodedStrEnum):
    """Spell affect bit on a character or granted by an object (affected_bits[])."""

    undefined = 'undefined*', 0
    blind = 'blind', 1
    invisible = 'invisible', 2
    detect_evil = 'detect-evil', 3
    detect_invisible = 'detect-invisible', 4
    detect_magic = 'detect-magic', 5
    sense_life = 'sense-life', 6
    hold = 'hold', 7
    sanctuary = 'sanctuary', 8
    group = 'group', 9
    curse = 'curse', 10
    flying = 'flying', 11
    poison = 'poison', 12
    protect_evil = 'protect-evil', 13
    paralysis = 'paralysis', 14
    infravision = 'infravision', 15
    water_breath = 'water-breath', 16
    sleep = 'sleep', 17
    sneak = 'sneak', 18
    hide = 'hide', 19
    fear = 'fear', 20
    charm = 'charm', 21
    follow = 'follow', 22
    true_sight = 'true-sight', 23
    scrying = 'scrying', 24
    fireshield = 'fireshield', 25
    invulnerability = 'invulnerability', 26
    berserk = 'berserk', 27
    berserk_recover = 'berserk-recover', 28
    nosleep = 'nosleep', 29
    nosummon = 'nosummon', 30
    nocharm = 'nocharm', 31
    recharger = 'recharger', 32
    vitality = 'vitality', 33
    farsee = 'farsee', 34
    nofear = 'nofear', 35
    calm = 'calm', 36
    bit37 = 'bit37', 37    # no name in the C table
    bit38 = 'bit38', 38    # no name in the C table
    bit39 = 'bit39', 39    # no name in the C table
    no_poison = 'no-poison', 40
    bearform = 'bearform', 41
    catform = 'catform', 42
    boomform = 'boomform', 43
    treeform = 'treeform', 44
    normform = 'normform', 45
    bit46 = 'bit46', 46    # no name in the C table


class Immunity(CodedStrEnum):
    """Damage class for immune/resistant/susceptible (immunity_names[])."""

    fire = 'fire', 0
    cold = 'cold', 1
    electricity = 'electricity', 2
    energy = 'energy', 3
    blunt = 'blunt', 4
    pierce = 'pierce', 5
    slash = 'slash', 6
    acid = 'acid', 7
    poison = 'poison', 8
    drain = 'drain', 9
    sleep = 'sleep', 10
    charm = 'charm', 11
    hold = 'hold', 12
    non_magical = 'non-magical', 13
    plus_1 = 'plus 1', 14
    plus_2 = 'plus 2', 15
    plus_3 = 'plus 3', 16
    plus_4 = 'plus 4', 17
    backstab = 'backstab', 18
    n20 = '20', 19
    n21 = '21', 20
    n22 = '22', 21
    n23 = '23', 22
    n24 = '24', 23
    n25 = '25', 24
    n26 = '26', 25
    n27 = '27', 26
    n28 = '28', 27
    n29 = '29', 28
    n30 = '30', 29
    n31 = '31', 30
    n32 = '32', 31


class SectorFlag(CodedStrEnum):
    """Sector flag (sector_bits[])."""

    no_weather = 'no_weather', 0
    fly_only = 'fly_only', 1
    water_breath = 'water_breath', 2
    no_spells = 'no_spells', 3
    prototype = 'prototype', 4


class ClanFlag(CodedStrEnum):
    """Clan flag (clan_flags[])."""

    pkothers = 'pkothers', 0
    pkclan = 'pkclan', 1
    private = 'private', 2
    stealth = 'stealth', 3
    openenroll = 'openenroll', 4
    bit5 = 'bit5', 5    # no name in the C table


class TrapEffect(CodedStrEnum):
    """Trap effect flag (trap_eff_flags[])."""

    move = 'move', 0
    object = 'object', 1
    room = 'room', 2
    north = 'north', 3
    east = 'east', 4
    south = 'south', 5
    west = 'west', 6
    up = 'up', 7
    down = 'down', 8
    northeast = 'northeast', 9
    northwest = 'northwest', 10
    southeast = 'southeast', 11
    southwest = 'southwest', 12


class PlayerFlag(CodedStrEnum):
    """Player act flag (player_bits[])."""

    brief = 'BRIEF', 0
    noshout = 'NOSHOUT', 1
    compact = 'COMPACT', 2
    dontset = 'DONTSET', 3
    wimpy = 'WIMPY', 4
    nohassle = 'NOHASSLE', 5
    stealth = 'STEALTH', 6
    hunting = 'HUNTING', 7
    deaf = 'DEAF', 8
    echo = 'ECHO', 9
    log = 'LOG', 10
    noviewlog = 'NOVIEWLOG', 11
    banished = 'BANISHED', 12
    criminal = 'CRIMINAL', 13
    notell = 'NOTELL', 14
    auction = 'AUCTION', 15
    nosports = 'NOSPORTS', 16
    gossip = 'GOSSIP', 17
    silenced = 'SILENCED', 18
    veg = 'VEG', 19
    debug = 'DEBUG', 20
    noexits = 'NOEXITS', 21
    questing = 'QUESTING', 22
    police = 'POLICE', 23
    tester = 'TESTER', 24
    stupid = 'STUPID', 25
    regen = 'REGEN', 26
    priority = 'PRIORITY', 27
    badname = 'BADNAME', 28
    leash = 'LEASH', 29
    anonymous = 'ANONYMOUS', 30


class AccountFlag(CodedStrEnum):
    """Account flag (account_bits[])."""

    valid = 'VALID', 0
    nonew = 'NONEW', 1
    silenced = 'SILENCED', 2
    stupid = 'STUPID', 3
    banished = 'BANISHED', 4
    log = 'LOG', 5
    nopurge = 'NOPURGE', 6
    noshout = 'NOSHOUT', 7
    ver_exempt = 'VER_EXEMPT', 8
    ver_mailed = 'VER_MAILED', 9
    verified = 'VERIFIED', 10


class Form(CodedStrEnum):
    """Body form of a race (forms[])."""

    humanoid = 'humanoid', 0
    animal = 'animal', 1
    undead = 'undead', 2
    lycanthrope = 'lycanthrope', 3
    diabolic = 'diabolic', 4
    reptile = 'reptile', 5
    nohands = 'nohands', 6
    person = 'person', 7
    extra_planar = 'extra-planar', 8


class Intrinsic(CodedStrEnum):
    """Racial intrinsic ability (intrinsics[])."""

    infravision = 'infravision', 0
    regeneration = 'regeneration', 1
    fast_heal = 'fast-heal', 2


class ApplyLocation(CodedStrEnum):
    """What an apply modifies (apply_types[])."""

    none_ = 'NONE', 0
    str = 'STR', 1
    dex = 'DEX', 2
    int = 'INT', 3
    wis = 'WIS', 4
    con = 'CON', 5
    cha = 'CHA', 6
    lck = 'LCK', 7
    level = 'LEVEL', 8
    age = 'AGE', 9
    char_weight = 'CHAR_WEIGHT', 10
    char_height = 'CHAR_HEIGHT', 11
    mana = 'MANA', 12
    hit = 'HIT', 13
    move = 'MOVE', 14
    gold = 'GOLD', 15
    exp = 'EXP', 16
    all_ac = 'ALL_AC', 17
    hitroll = 'HITROLL', 18
    damroll = 'DAMROLL', 19
    saving_para = 'SAVING_PARA', 20
    saving_rod = 'SAVING_ROD', 21
    saving_petri = 'SAVING_PETRI', 22
    saving_breath = 'SAVING_BREATH', 23
    saving_spell = 'SAVING_SPELL', 24
    saving_all = 'SAVING_ALL', 25
    resistance = 'RESISTANCE', 26
    susceptibility = 'SUSCEPTIBILITY', 27
    immunity = 'IMMUNITY', 28
    spell_affect = 'SPELL AFFECT', 29
    weapon_spell = 'WEAPON SPELL', 30
    eat_spell = 'EAT SPELL', 31
    backstab = 'BACKSTAB', 32
    kick = 'KICK', 33
    sneak = 'SNEAK', 34
    hide = 'HIDE', 35
    bash = 'BASH', 36
    pick = 'PICK', 37
    steal = 'STEAL', 38
    track = 'TRACK', 39
    hit_n_dam = 'HIT-N-DAM', 40
    feet_ac = 'FEET-AC', 41
    legs_ac = 'LEGS-AC', 42
    arms_ac = 'ARMS-AC', 43
    body_ac = 'BODY-AC', 44
    head_ac = 'HEAD-AC', 45
    all_stopping = 'ALL-STOPPING', 46
    feet_stopping = 'FEET-STOPPING', 47
    legs_stopping = 'LEGS-STOPPING', 48
    arms_stopping = 'ARMS-STOPPING', 49
    body_stopping = 'BODY-STOPPING', 50
    head_stopping = 'HEAD-STOPPING', 51
    batter = 'BATTER', 52
    power = 'POWER', 53
    fire_resist = 'FIRE RESIST', 54
    cold_resist = 'COLD RESIST', 55
    electric_resist = 'ELECTRIC RESIST', 56
    energy_resist = 'ENERGY RESIST', 57
    acid_resist = 'ACID RESIST', 58
    poison_resist = 'POISON RESIST', 59
    force_resist = 'FORCE RESIST', 60
    magic_resist = 'MAGIC RESIST', 61
    all_resists = 'ALL RESISTS', 62
    item_spell = 'ITEM SPELL', 63
    assassinate = 'ASSASSINATE', 64
    melee_haste = 'MELEE_HASTE', 65
    spell_haste = 'SPELL_HASTE', 66
    slow = 'SLOW', 67
    armor_penetration = 'ARMOR PENETRATION', 68
    fire_penetration = 'FIRE PENETRATION', 69
    cold_penetration = 'COLD PENETRATION', 70
    electricity_penetration = 'ELECTRICITY PENETRATION', 71
    water_penetration = 'WATER PENETRATION', 72
    acid_penetration = 'ACID PENETRATION', 73
    poison_penetration = 'POISON PENETRATION', 74
    force_penetration = 'FORCE PENETRATION', 75
    magic_penetration = 'MAGIC PENETRATION', 76
    light_penetration = 'LIGHT PENETRATION', 77
    dark_penetration = 'DARK PENETRATION', 78
    spell_power = 'SPELL POWER', 79
    water_resist = 'WATER RESIST', 80
    light_resist = 'LIGHT RESIST', 81
    life_steal = 'LIFE STEAL', 82
    penetrate_all = 'PENETRATE ALL', 83
    spell_vamp = 'SPELL VAMP', 84
    mana_regen = 'MANA REGEN', 85
    power_regen = 'POWER REGEN', 86
    hp_regen = 'HP REGEN', 87
    moves_regen = 'MOVES REGEN', 88
    all_attributes = 'ALL ATTRIBUTES', 89
    slicendice = 'SLICENDICE', 90
    daze = 'DAZE', 91
    cheapshot = 'CHEAPSHOT', 92
    preparation = 'PREPARATION', 93
    garrote = 'GARROTE', 94
    ambush = 'AMBUSH', 95
    vanish = 'VANISH', 96
    shadowform = 'SHADOWFORM', 97
    strike = 'STRIKE', 98
    crippling_strike = 'CRIPPLING STRIKE', 99
    holy_strike = 'HOLY STRIKE', 100
    mute_strike = 'MUTE STRIKE', 101
    peek = 'PEEK', 102
    whirlwind = 'WHIRLWIND', 103


class PulseType(CodedStrEnum):
    """What a pulse affect does on each pulse (PULSE_TYPE_*)."""

    none_ = 'none', 0
    buff = 'buff', 1
    heal = 'heal', 2
    damage = 'damage', 3
    shield = 'shield', 4


class WearPosition(CodedStrEnum):
    """Equipment slot (WEAR_* / WIELD / HOLD / POUCH), code 0..21."""

    light = 'light', 0
    finger_r = 'finger_r', 1
    finger_l = 'finger_l', 2
    neck_1 = 'neck_1', 3
    neck_2 = 'neck_2', 4
    body = 'body', 5
    head = 'head', 6
    legs = 'legs', 7
    feet = 'feet', 8
    hands = 'hands', 9
    arms = 'arms', 10
    shield = 'shield', 11
    about = 'about', 12
    waist = 'waist', 13
    wrist_r = 'wrist_r', 14
    wrist_l = 'wrist_l', 15
    wield = 'wield', 16
    hold = 'hold', 17
    pouch = 'pouch', 18
    wings = 'wings', 19
    trinket_r = 'trinket_r', 20
    trinket_l = 'trinket_l', 21


class ConfigFlag(CodedStrEnum):
    """Player display/behaviour preference (CONFIG_*)."""

    map_ = 'map', 0
    manual_unlock = 'manual_unlock', 1
    auto_split = 'auto_split', 2
    short_descs = 'short_descs', 3
    timestamps = 'timestamps', 4
    keywords = 'keywords', 5
    hunger = 'hunger', 6
    channames = 'channames', 7


class LogFlag(CodedStrEnum):
    """Server log channel (LOG_*)."""

    connection = 'connection', 0
    mortspy = 'mortspy', 1
    immspy = 'immspy', 2
    urgent = 'urgent', 3
    debug = 'debug', 4
    reject = 'reject', 5
    misc = 'misc', 6
    death = 'death', 7
    bugs = 'bugs', 8
    ideas = 'ideas', 9
    typos = 'typos', 10
    thief = 'thief', 11
    fine = 'fine', 12
    link = 'link', 13
    fall = 'fall', 14
    banished = 'banished', 15
    cheat = 'cheat', 16
    imp = 'imp', 17
    account = 'account', 18
    load_obj = 'load_obj', 19
    malloc = 'malloc', 20
    aloginout = 'aloginout', 21
    delete = 'delete', 22
    zone = 'zone', 23
    quest = 'quest', 24
    police = 'police', 25
    consent = 'consent', 26
    board = 'board', 27
    teleport = 'teleport', 28
    help = 'help', 29
    pulseaff = 'pulseaff', 30
    mobcast = 'mobcast', 31


class ClanRank(CodedStrEnum):
    """Rank within a clan (clan_ranks[])."""

    member = 'Member', 0
    officer = 'Officer', 1
    leader = 'Leader', 2
    owner = 'Owner', 3


_ALIAS_CODES[MobAction] = {15: 'polymorphed'}
