#!/bin/sh
# PR_HOME is the directory that holds live/ and Backups/; defaults to the
# current directory. Works inside the data directory (stash/, PURGED/).
PR_HOME="${PR_HOME:-$(pwd)}"; export PR_HOME
PR_LIB="${PR_LIB:-$PR_HOME/live/lib}"
cd "$PR_LIB" || exit 1

# Default backup: the newest players_*.tar.gz in Backups/ (see -f).
FILE=$(ls -t "$PR_HOME"/Backups/players_*.tar.gz "$PR_HOME"/Backups/players_*.tar 2>/dev/null | head -n 1)
# be sure to change this next line to point to where the backup file is
# and the backup should be created with the following commands:
# cd PR/lib
# tar -cf Players.tar stash
# gzip Players.tar
# mv Players.tar.gz $HOME/backup


if [ $# -gt 1 -a "$1" = "-f" ]
then
  FILE=$2
  echo "Using $FILE as backup."
  shift 2
fi

if [ $# -eq 0 ]
then
  echo "Usage: "`basename $0`" [-f backupfile] player1 [player2 [player3 [...]]]"
  exit 1
fi


ARGS=""
for i in $*
do
  FILENAME="stash/`echo $i | cut -c-1`/$i"
  if [ -f $FILENAME ]
  then
    echo "$FILENAME exists"
    /bin/echo -n "Overwrite? "
    read a
    if [ "$a" = "y" ]
    then
      ARGS="$ARGS $FILENAME"
    fi
  else
    ARGS="$ARGS $FILENAME"
  fi
done

echo "About to extract:"
echo $ARGS
/bin/echo -n "Press enter to begin or q to abort: "
read a
if [ "$a" = "q" ]
then
  echo "Restore aborted."
  exit 1
fi

echo "tar -xvzf $FILE $ARGS"
tar -xvzf $FILE $ARGS
